### ISSUE TITLE
Midtown Madness 2 Fatal Error

### ISSUE THREAD

**Issue by greasythemattis** [narzoul/DDrawCompat#1]
Game starts and before entering the menu loading bar stops and gives the following error
http://imgur.com/sUL9Qut

SystemSpecs by DxDiag
http://pastebin.com/3WCkMQHq

ddraw log

6412 10:31:54.434 Process path: C:\Program Files (x86)\Microsoft Games\Midtown Madness 2\Midtown2.exe
6412 10:31:54.434 Loading DDrawCompat from C:\Program Files (x86)\Microsoft Games\Midtown Madness 2\DDRAW.DLL
6412 10:31:54.450 DDrawCompat loaded successfully
6412 10:31:54.450 Installing DirectDraw hooks
6412 10:31:54.518 Installing GDI hooks
6412 10:31:54.550 Installing registry hooks
6412 10:31:54.550 Finished installing hooks
6412 10:32:03.301 GDI used DC cache size: 1
6412 10:33:09.769 Detaching DDrawCompat
6412 10:33:09.796 DDrawCompat detached successfully

-EDIT-
Off topic.
Hey Narzoul would like to let you know that your project is the only that made the Settlers IV work correctly on Windows 10 here.I'm really, really glad you made this.Thanks a lot!

-EDIT2-
I should also mention that without DDrawCompat the game launchs but with frame issues and invisible menu.

**Comment by narzoul** [comment]
I don't have the full game but the trial version has similar problems for me, except I don't even see a load screen, just a small blue bar at the bottom on a black screen (or is that supposed to be the progress bar you were talking about?).

Without DDrawCompat the game works fine though even in the menu, except for performance issues. There is no load screen when starting the game at all (or maybe it just flashes by too fast during the display mode switch).

I'll see what I can do.

I'm glad you got Settlers IV working because it still doesn't work for me. :) ("Error initializing Graphic Interface", GOG version). I was going to look into that some day too...

**Comment by narzoul** [comment]
Meanwhile, an alternative you could try (without DDrawCompat) is to set some compatibility settings via the Compatibility Administrator of the Microsoft Application Compatibility Toolkit. If you don't have it, you can download it as part of the [Windows Assessment and Deployment Kit (ADK) for Windows 10](http://go.microsoft.com/fwlink/p/?LinkId=526740). Make sure you only select the ACT component during installation, otherwise it will be a huge download.

Launch the Compatibility Administrator (32-bit), click Fix, enter some name and target the main exe file of the game. Then from the next page I think you'll definitely need to check "Disable8And16BitD3D" to fix the performance issues, and from the page after that "DXPrimaryEmulation" may be useful with the Command Line set to "-DisableMaxWindowedMode" (without quotes) under Parameters. The latter may or may not fix the menu visibility (I can't confirm as I don't have that problem either with or without this option).

**Comment by greasythemattis** [comment]
Yes the blue bar was supposed to be the loading bar.
Game is running flawless with only this option "Disable8And16BitD3D" checked.
Thanks!

**Comment by narzoul** [comment]
I fixed this problem on my end with the mentioned commit, at least in the trial version.
I would appreciate it if you could verify it with the full version on your system as well.
If you can't compile the code yourself, just wait for the next binary release.
