### ISSUE TITLE
The Sims 1 Compatibility

### ISSUE THREAD

**Issue by thesammy58** [narzoul/DDrawCompat#103]
First off, thanks so much for this. DDrawCompat has to be one of the few, if not the ONLY wrapper available on the internet right now that gets The Sims 1 to run at a solid 60 FPS on Windows 8/10. I tried dgVoodoo but had no luck increasing the framerate. I actually just signed up for GitHub simply to praise you for your work here and to make a few comments:

-Using your wrapper causes the loading screen of the game to move in an extremely choppy/laggy manner, however everything after this initial loading screen is fine, so obviously this isn't a major deal. Just found that odd when the loading screen has to be the least graphically-advanced thing in the game.

-The one major detail I personally found dgVoodoo to have over this wrapper was the ability to force anti-aliasing in the game, but unfortunately I can only use one DDraw file at a time lol, and I would choose yours first. Unfortunately it's really hard to find an AA work-around that supports pre-DX9 applications.

**Comment by mrpenguinb** [comment]
dgVoodoo2 has poor DirectDraw translation/emulation overall. The game runs super smoothly on Windows 10, it's unbelievable. Did you find out about DDrawCompat via PCGamingWiki's wiki page for The Sims 1?

I have noticed the same choppy initial loading screen text, one of the only performance issues I have encountered in 5-10 hours of gameplay. Large lots with lots of sims can lag, but that might be down to the game itself not being entirely optimized for better hardware.

To get anti-aliasing, if you have an NVIDIA GPU, NVIDIA Profile Inspector or the NVIDIA Control Panel might be able to force it.

**Comment by narzoul** [comment]
I guess the choppy loading screen is caused by the single CPU core affinity set by default. Try setting CpuAffinity=all in v0.4.0.
Antialiasing is particularly troublesome in this game, because it uses a software Direct3D rendering device. I added a bunch of settings to try to force this to work anyway in v0.4.0:
SoftwareDevice=hal
PalettizedTextures=on
ResolutionScale=display(1)   # optional, but increases rendering resolution to your native display resolution
ResolutionScaleFilter=bilinear
Antialiasing=msaa4x   # or any other setting

Note that antialiasing still won't work in Sims 1 on some GPUs, because the game requires CPU access to depth buffers, and some GPUs (e.g. all NVIDIA, I think) cannot resolve multisampled depth buffers in Direct3D 9. Enabling antialiasing in this case will make the characters disappear. You can use ResolutionScale=display(4) or similar instead of antialiasing in this case.

**Comment by mrpenguinb** [comment]
With the latest release of DDrawCompat, 0.4.0 the game stutters significantly more. Also is there a way to disable the new overlay? (if not then maybe it's causing issues?)

**Comment by narzoul** [comment]
Is this with the default configuration, or have you tried my suggestions above? Please post system specs and config(s) you've tested, and steps to reproduce the issue, since I haven't noticed any stuttering yet on my end, but I haven't played the game much.

The overlay is unrelated to performance unless you keep it open.

**Comment by mrpenguinb** [comment]
Default configuration and the suggestions you provided above.
My system specs are: Intel i5-10600K, NVIDIA GTX 1050 Ti (4GB) and 32GB of RAM. My monitor is 1440p.
There's a lot of latency just in the neighborhood screen (after the loading screen). When in a house, it's even worse when moving the camera around (right-click dragging).
