### ISSUE TITLE
OBS Studio recording

### ISSUE THREAD

**Issue by pilotS1** [narzoul/DDrawCompat#109]
Hello and thanks for the awesome work, when I am using ddrawcompat the game displays normal but in obs the window capture displays just a white window, anybody encountered that before?

**Comment by narzoul** [comment]
If you're talking about windowed mode, DDrawCompat redirects that to layered windows that are directly above the original window, and that's where all the content is displayed. The real window underneath would be mostly empty, except for some drawing that may be done from kernel mode that cannot be hooked by DDrawCompat.

If this is the case, try using "display capture" instead, that seems to work for me, although it may be a hassle to crop it to a single window.

If it's about full-screen mode, I'm not sure if OBS can capture that because it uses exclusive full-screen mode, unlike native ddraw which uses a fake full-screen mode (borderless windowed). But I seem to recall in some other thread here, someone mentioned that it was working as well...

**Comment by narzoul** [comment]
Display capture should work fine now in the default borderless fullscreen mode of v0.4.0, Window capture is not yet supported. I will consider adding some setting for that in the future, but it's going to have some limitations anyway (e.g. no GDI interworking support).

**Comment by narzoul** [comment]
Window capture now also works in v0.5.0, using the alternative windows with the "[DDrawCompat]" prefix as the capture source. That's about the best I can do here.
