### ISSUE TITLE
Tom Clancy's Rainbow Six Rogue Spear graphical glitches

### ISSUE THREAD

**Issue by BEENNath58** [narzoul/DDrawCompat#113]
While playing Rogue Spear with the HW/SW renderer, some minor texture issues occur where they disappear completely.

This is how it looks:
![IMG20210912221139](https://user-images.githubusercontent.com/64649734/132996269-bdf7e1ec-6617-4b11-b285-a64a028c5628.jpg)

This is the proper textures:
![IMG20210912221145](https://user-images.githubusercontent.com/64649734/132996274-5d01d28c-c04f-4c87-b742-b6cdd28b5b8b.jpg)

It would be great to eliminate this issue. Even greater would be, to eliminate additional major graphical glitches under Software Renderer while using resolution over 640x480
![IMG20210912221344](https://user-images.githubusercontent.com/64649734/132996342-b2fe20e6-d03e-4cce-901b-8531eb82ede7.jpg)

**Comment by narzoul** [comment]
For the disappearing texture, try the FaultTolerantHeap shim from Microsoft ACT as mentioned in this old comment: https://github.com/narzoul/DDrawCompat/issues/2#issuecomment-280867054
I never had time or much patience to debug it since the shim fixes the issue anyway, and I always assumed it's a bug in the game that I couldn't fix from the wrapper.

I'd assume the software renderer is also a game specific bug, since there aren't any changes to the native Direct3D RGB software device in DDrawCompat. However, I'm not aware of any way to fix it either (FaultTolerantHeap doesn't help). Out of curiosity, why would you want to use it if the hardware renderer works?

**Comment by BEENNath58** [comment]
Neat! The shim actually worked. 

It would be great to have both renderers working, even if it not required. Lie we could then say Rogue Spear completely works on new Windows.

**Comment by narzoul** [comment]
I checked the software rendering in a WinXP VM and it has the exact same issues there with resolutions other than 640x480, so I'm pretty sure it's just broken in the game itself. It looks like it messes up the z-buffer via CPU access or something similar, so I don't think it can be fixed from a wrapper.
