### ISSUE TITLE
OBS with Age of empires: The rise of Rome.

### ISSUE THREAD

**Issue by 9xtiger** [narzoul/DDrawCompat#114]
Windows 10, ingame play it show nomal when i show the timeline. But in OBS it keep flicking the screen when i show timeline. I use display capture.

**Comment by narzoul** [comment]
It may be an issue with capturing exclusive fullscreen mode DirectDraw games in OBS. v0.4.0 now has borderless fullscreen mode by default, which may help. But even if it doesn't, I'm no longer attempting to support external hooks in conjunction with DDrawCompat, since it's an endless fight with hooks in other software and I don't have time to guarantee backward compatibility with everything after each change.
