### ISSUE TITLE
Jagged Alliance 2, Slow Laptop and Sector Loading

### ISSUE THREAD

**Issue by nexitem** [narzoul/DDrawCompat#14]
Some things including Laptop opening and Sector loading seem to be slow. This is only a problem in this wrapper however everything else works fine and I'm quite happy.

Current workaround for me is to set the CPU core count to maximum ( or at least 2 cores ) and the problem disappears.

I think your wrapper could really benefit from some kind of simple configuration file. Good work!

**Comment by narzoul** [comment]
There are similar issues with a few other games that I've noticed. Of course, I doubt these old DirectDraw games really need multiple cores to run efficiently on modern systems. In the other cases that I've already investigated, the problem always seemed to be caused by some busy waiting loops that apparently keep some threads running for much longer time chunks than they should, which then causes other threads to be starved. Maybe it's some change in the CPU scheduler introduced in recent years into the OS.

I've already had some plans to resolve these issues (without having to go multi-core if possible), once I get around to implementing it I'll see if it resolves this one too. Luckily I have the full game available for testing.

**Comment by nexitem** [comment]
Well so far your wrapper is the one that works almost without any problems or crashes even on some other games I tried.

**Comment by narzoul** [comment]
I can't reproduce either of these problems with the demo or the full version (GOG). Loading and laptop opening speeds are the same with one or all cores. Please give some more info about your system:
- Version of the game used and any patches installed
- Version of DDrawCompat used
- Windows version
- GPU model
