### ISSUE TITLE
Dynamic index and vertex buffers not available

### ISSUE THREAD

**Issue by watercannons** [narzoul/DDrawCompat#155]
Hi, first of all thank you for all the work you've put in DDrawCompat, it's the go to whenever I want to install Command & Conquer Red Alert 2 and Yuri's Revenge. I did encounter an issue(?) recently though with the latest version 0.4.0. Whenever I try to launch the game using the DLL, I get a "Dynamic Index Buffers Not Available" message in the logs, the same is for vertex buffers (see the log file with IntelXe suffixed). This doesn't happen in 0.3.x. The system I'm running off of has a i7-1160g7 w/ Intel Xe, and interestingly when I run it off of an AMD GPU (rx 6900xt on my desktop) I have no problems with 0.4.0 (see the log file with AMDNavi suffixed) and the 0.3.x versions. I did some GPU driver cleaning + win10 reinstall and that didn't seem to help, so I'm just submitting this to see if this is a platform specific bug.

[DDrawCompat-gamemd_AMDNavi.log](https://github.com/narzoul/DDrawCompat/files/9769363/DDrawCompat-gamemd_AMDNavi.log)
[DDrawCompat-gamemd_IntelXe.log](https://github.com/narzoul/DDrawCompat/files/9769364/DDrawCompat-gamemd_IntelXe.log)

**Comment by narzoul** [comment]
Could you please upload debug logs for both v0.3.2 and v0.4.0 with the Intel GPU?

I definitely remember with my old Intel HD4000 (which I no longer have unfortunately) at least dynamic index buffers weren't available even in v0.3.1 (some unnecessary driver restriction for DX7 I guess, since they were available for DX9), but from looking at some old logs I got from others, it looks like vertex buffers weren't available either. Anyway, I'm not sure that's the issue, you seem to be having some crash or other problem instead because some other stuff is missing from your logs as well (e.g., supported resource formats).

**Comment by narzoul** [comment]
Closing due to no response.
