### ISSUE TITLE
Black artifacts on the projected headlights in Need for Speed 3 and 4

### ISSUE THREAD

**Issue by PlayNeth** [narzoul/DDrawCompat#164]
I'm currently using the latest version of DDrawCompat, was told that this weird artifact is a result of a Texel misalignment in later versions of DirectX, but no matter what I enable, I can't seem to get rid of this issue, even with AlternatePixelCenter set to on. 
Although it actually does fix the blurriness in the menu and fonts it doesn't seem to address the projected headlights in both games.
Here's my global settings file:
[DDrawCompat.txt](https://github.com/narzoul/DDrawCompat/files/10085319/DDrawCompat.txt)
And a video showcasing the issue:
https://youtu.be/RQsT7jZD45Y

**Comment by narzoul** [comment]
AlternatePixelCenter is for 2D rendered stuff only (like text) so I'm not surprised it doesn't fix it. Where did you get that it's a texel misalignment issue? Is there a technical description of the problem somewhere? Based on some googling, the "modern patch" might fix this problem, did you try that already?

**Comment by PlayNeth** [comment]
> AlternatePixelCenter is for 2D rendered stuff only (like text) so I'm not surprised it doesn't fix it. Where did you get that it's a texel misalignment issue? Is there a technical description of the problem somewhere? Based on some googling, the "modern patch" might fix this problem, did you try that already?

I was told on the Classic NFS discord that back in the day this issue could be fixed by setting the Texel Alignment to 0 instead of the default value of 3 in the driver settings, but sadly that isn't supported whatsoever by modern cards, and since NFS2-5 need this value at zero to render the headlights and text properly you get those artifacts. AlternatePixelCenter does indeed fix the blurry and janky text but makes no difference on the headlights, and that has driven me basically clueless.
And yes, I've tried the modern patch already and the problem is still present there with all the default DirectX renderers.
![image](https://user-images.githubusercontent.com/82559127/203864512-c48f8afa-5acc-4983-814c-c7606f7a9315.png)

**Comment by narzoul** [comment]
Thanks for the tips, using a 16-bit depth buffer definitely reduces the problem with DX5, but doesn't eliminate it. DX6 and DX7 are already using 16-bit, at least on my system.

Unfortunately, I couldn't find a solution by playing around with texture coordinates or texture clamping. I'm not exactly sure what that Texel Alignment setting was supposed to change.

Anyway, it seems that the issue is highly resolution dependent. At 640x480, setting the resolution scale factor to at least 3 pretty much eliminates all Z-fighting with 16-bit depth buffers. Try ResolutionScale=app(3) or greater. Increasing the in-game resolution seems to help in a similar way.

Here's a temporary patch to force using 16-bit depth buffers anyway (for DX5):
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/10097059/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/10097061/diff.txt) compared to v0.4.0)

**Comment by PlayNeth** [comment]
> Thanks for the tips, using a 16-bit depth buffer definitely reduces the problem with DX5, but doesn't eliminate it. DX6 and DX7 are already using 16-bit, at least on my system.
> 
> Unfortunately, I couldn't find a solution by playing around with texture coordinates or texture clamping. I'm not exactly sure what that Texel Alignment setting was supposed to change.
> 
> Anyway, it seems that the issue is highly resolution dependent. At 640x480, setting the resolution scale factor to at least 3 pretty much eliminates all Z-fighting with 16-bit depth buffers. Try ResolutionScale=app(3) or greater. Increasing the in-game resolution seems to help in a similar way.
> 
> Here's a temporary patch to force using 16-bit depth buffers anyway (for DX5): [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/10097059/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/10097061/diff.txt) compared to v0.4.0)

Awesome. Btw out of curiosity, do things improve when you force 24-bit depth?

**Comment by narzoul** [comment]
No, it makes it worse, like on DX5 without forced 16-bit (which defaults to 24-bit). And 32-bit is even worse, though I could only try a floating-point format. Neither of them is fixable with higher resolutions either.

**Comment by PlayNeth** [comment]
I asked around in the server a little bit further and someone sent me a screenshot of the option that used to be a thing in earlier DirectX versions:
![image](https://user-images.githubusercontent.com/82559127/204111390-4bd8e049-29de-44c5-ad93-efae9519f98a.png)
Games need a value of 0 set in this according to him. I can't find any documentation whatsoever on this issue, so this is the best I've got atm.

**Comment by narzoul** [comment]
Yes, I've seen that screenshot already. There's also some more description here: https://download.nvidia.com/Windows/45.23/NVIDIA_Display_Properties_Users_Guide_v45.23.pdf

But it makes no sense to me. The default value 3 is supposed to "conform to the Direct3D specifications", but the value 3 is between the "Center" and "Upper Left Corner" labels, which definitely doesn't sound like any standard I know of.

Anyway, there are 2 kinds of offsets like this implemented in DDrawCompat. One is the AlternatePixelCenter setting, which simply offsets pre-transformed vertex coordinates by half a pixel. I experimented with adding a customizable offset between -0.5 and +0.5 with increments of 0.01, but it doesn't do anything about the projected headlight artifacts, it still only affects the HUD and text sharpness.

The other setting is the SpriteTexCoord setting, in particular at the "round" value, which already has this kind of offset parameter. It offsets texture coordinates at vertices, instead of offsetting the vertices themselves. It currently only affects sprites and also applies a rounding after the offset. I've experimented with removing the rounding and extending it to all vertices, not just sprites. But it pretty much has the same effect as AlternatePixelCenter, only the text becomes sharper or blurrier. The headlight positions shift around a little, but the artifacts remain the same.

I don't know what else to make of it. I can't think of any other kind of offsetting to try. I have doubts that this setting ever actually fixed projected headlights completely, and maybe it was just meant to make the text sharper. But I don't have such old hardware and software to test.

Anyway, since resolution scaling or setting a higher in-game resolution seems to solve the issue, I'm rather content with this workaround currently.

**Comment by PlayNeth** [comment]
Unfortunate. Thank you for looking into the issue though. Gonna just blame the game's spaghetti code at this point lol

**Comment by narzoul** [comment]
You can now force 16-bit depth buffers with the [DepthFormat](https://github.com/narzoul/DDrawCompat/wiki/Configuration#depthformat) setting in v0.5.0.

**Comment by PlayNeth** [comment]
Sorry to necro this post, but I feel this might be worth checking out.

Turns out Porsche Unleashed relies on the same texture technique for the project headlights, but here's the thing: when running the game raw, with some ACT patches the issue with the black dots go away (same symptoms of the other two games).

EmulateHeap + DXEmulateSurface -DisableMaxWindowedMode + SingleProcAffinity should be enough to get the game up and running, and the projected headlights work as intended.

I'm just really curious what exactly causes this issue, as setting the DepthBuffer to 16 in DDC or any other wrapper isn't enough to fix the black dots on there. And unlike the other two games it seems to be way easier and consistent to reproduce with PU to attempt debugging it.
