### ISSUE TITLE
Janes F-18 HUD graphic problem

### ISSUE THREAD

**Issue by ahmadmuzaffarzafriy** [narzoul/DDrawCompat#175]
The ddraw file runs the game fine, but the cockpit HUD in-game has some slight problem...

Also, why is it when trying to print screen the game when using the ddraw, the clipboard is either blank or black...

**Comment by narzoul** [comment]
Do you mean the unreadable text in the top-middle part?
![janesfa18](https://user-images.githubusercontent.com/16432233/210281226-2f150688-bcf2-472f-912e-766bdd85de64.jpg)

Screenshots should work just fine with v0.4.0, as you can see. Did you modify the default DDrawCompat settings perhaps?

The HUD also seems to render correctly with v0.3.2, but screenshots won't work with that (since it only supports exclusive fullscreen mode). I'll try to find what broke the HUD in v0.4.0.

**Comment by narzoul** [comment]
I found the culprit. The game uses automatically generated texture coordinates, which is incompatible with an optimization I implemented in v0.4.0. For now, I'll just disable that optimization as a quick fix, but I'll try to do something more sophisticated for the next release:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/10347996/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/10347999/diff.txt) compared to v0.4.0)

**Comment by narzoul** [comment]
Fixed in v0.5.0.
