### ISSUE TITLE
Another Mig Alley Issue / Request

### ISSUE THREAD

**Issue by WesCov** [narzoul/DDrawCompat#176]
Hi,

I have a Dell laptop running Windows 11 with a generic display adaptor (Intel UHD 620).

I can run Rowan's Mig Alley with the 1.23 patch applied in Windows 8 compatibility mode with your DDrawCompat v0.4.0.  (Thank you!) The attached file "DDrawCompat-Mig #1.log" logs the successful run.

After I apply the BDG patch (bdg_migalley_0.85f), the program starts with a white screen (with some misplaced navigator menus) and simply goes back to the file navigator.  The attached file "DDrawCompat-Mig #2.log" logs the failed run.  I think the only difference between the logs are that these last two lines are only in the successful run:

11:23:28.914 Using Direct3D device type: IID_IDirect3DHALDevice
11:23:53.203 DDrawCompat detached successfully

The mig alley community recommends adding a trio of files, always packaged together:  ddraw.dll, libwine.dll, and wined3d.dll.  I am pretty sure that the ddraw.dll is not yours but I can't find the files' source.  When I add them to the directory, mig alley starts up with all the game menus but the 3d environment will not display -- the sound is in the background but the splash screen doesn't go away.  I do not see a log file from this run.  This situation is the same as described in Issue #129 but I don't have an NVIDIA graphics card so the G-Sync solution doesn't work, and the ddraw is not yours anyway.

My hope is that you can suggest how to get your dll to work with the last patch, or your dll can be modified, so that the trio of files are not needed.  The reason that I would like the additional patch applied is that it allows for joysticks to be used whereas the unpatched version only accepts keyboard input.

Please let me know if there is more information I can supply.  I wish I could help more more but your skills are way past my capabilities.

Thanks much.

[DDrawCompat-Mig #1.log](https://github.com/narzoul/DDrawCompat/files/10322788/DDrawCompat-Mig.1.log)
[DDrawCompat-Mig #2.log](https://github.com/narzoul/DDrawCompat/files/10322789/DDrawCompat-Mig.2.log)

**Comment by witchiewoman** [comment]
It doesnt work for me eithr, white screen then CTD

**Comment by witchiewoman** [comment]
try deleting dbghelp in your folder, sometimes that works.

**Comment by WesCov** [comment]
Thanks for the suggestion but it did not work.  Another tip is to turn off the intro video in the bdg.txt file and this did not work either.  It still flashes a white screen then disappears.

**Comment by witchiewoman** [comment]
heres my logs, i may be an intel driver problem which is weird because I do not use it, I use my nvidia GTX 2070 but something is pointing to intel and buffer issues whn starting many of these ddraw games.


Mig.exe caused a EXCEPTION_ACCESS_VIOLATION in module Mig.exe at 0023:0051A205, direct_draw::MakeColourRangeFadeTable()+325 byte(s), T:\mig\SRC\hardware\..\HARDWARE\Win3d.cpp, line 15861
Exception handler called in drawloop.
Read from location 0da26ec8 caused an access violation.
Code: 66 0f b6 07 8b 4c 24 2c 66 0f b6 2e 23 c1 0f bf 
Stack dump:
Stack: 0023:0051A205 (0x00000010 0x0062FAE8 0x0000A97F 0x00000084) Mig.exe, direct_draw::MakeColourRangeFadeTable()+325 byte(s), T:\mig\SRC\hardware\..\HARDWARE\Win3d.cpp, line 15861
Stack: 0023:004F5DBA (0x0062FAE8 0x0000A97F 0x00000084 0x00009A87) Mig.exe, Display::MakeColourRangeFadeTable()+58 byte(s), T:\mig\SRC\hardware\..\HARDWARE\Hardwin.cpp, line 1530
Stack: 0023:004EF9C8 (0x0062FAE8 0x0000A97F 0x00000084 0x00009A87) Mig.exe, Display::DoMakeColourRangeFadeTable()+40 byte(s), T:\mig\SRC\graphics\..\GRAPHICS\Wrapper.cpp, line 1324
Stack: 0023:004E807B (0x0000A97F 0x00000084 0x00009A87 0x0000017F) Mig.exe, polygon::createpoly()+107 byte(s), T:\mig\SRC\graphics\..\GRAPHICS\Polygon.cpp, line 445
Stack: 0023:00464B81 (0x00661CC0 0x0C71FDB4 0x00661CE6 0x0042F745) Mig.exe, LandScape::InfiniteStrip()+5681 byte(s), T:\mig\SRC\3d\..\3D\Landscap.cpp, line 5305+37 byte(s)
Stack: 0023:0045BFCB (0x0C71FE1C 0x0C13F3F0 0x02B02478 0x00661CE2) Mig.exe, LandScape::RenderLandscape()+267 byte(s), T:\mig\SRC\3d\..\3D\Landscap.cpp, line 247
Stack: 0023:0042F745 (0x0C71FE1C 0x0C13F3F0 0x0B498040 0xFFFFFFFF) Mig.exe, ThreeDee::render3d()+1333 byte(s), T:\mig\SRC\3d\..\3D\3dcode.cpp, line 790
Stack: 0023:00432625 (0x0C71FE1C 0x0C13F3F0 0x0B498040 0x0BE54B98) Mig.exe, ThreeDee::render()+261 byte(s), T:\mig\SRC\3d\..\3D\3dcode.cpp, line 3306
Stack: 0023:00418CD4 (0x02B32778 0xFD9F2A92 0x74C08520 0x5CC46F80) Mig.exe, View3d::drawloop()+308 byte(s), T:\mig\SRC\MFC\..\MFC\Stub3d.cpp, line 1286
Stack: 0023:5CC47086 (0x0019FA6C 0xC8C82F55 0x74C08520 0x74C08520) MFC42.DLL
Stack: 0023:74C084B5 (0x0C71FF84 0x74C87D69 0x0BE585A8 0x74C87D50) msvcrt.dll, beginthreadex()+213 byte(s)
Stack: 0023:74C08581 (0x0BE585A8 0x74C87D50 0x0C71FFDC 0x76EEBB9B) msvcrt.dll, endthreadex()+145 byte(s)
Stack: 0023:74C87D69 (0x0BE585A8 0x373123E1 0x00000000 0x00000000) KERNEL32.DLL, BaseThreadInitThunk()+25 byte(s)
Stack: 0023:76EEBB9B (0xFFFFFFFF 0x76F18DF1 0x00000000 0x00000000) ntdll.dll, RtlInitializeExceptionChain()+107 byte(s)
Stack: 0023:76EEBB1F (0x00000000 0x00000000 0x00000000 0x00000000) ntdll.dll, RtlClearBits()+191 byte(s)

Stack dump (old format):
0c71ffe4: ffffffff 76f18df1 00000000 00000000 74c08520 0be585a8 00000000

EAX=00000000  EBX=0DA04A58  ECX=0C710000  EDX=0DA24E48  ESI=0DA26298
EDI=0DA26EC8  EBP=0C71FFEC  ESP=0C71FFE4  EIP=76EEBB1F  FLG=00010202
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
Error occurred at 1/3/2023 20:23:12.
C:\Rowan\mig\Mig.exe, run by minau.
12 processor(s), type 586.
2048 MBytes physical memory.
OS: 6.2 build 9200 platform 2 

	Module list: names, addresses, sizes, time stamps and file times:
C:\Rowan\mig\Mig.exe, loaded at 0x00400000 - 2793508 bytes - 42768b17 - file date is 5/2/2005 12:18:34
C:\rowan\mig\English\text\miglang.dll, loaded at 0x03e00000 - 487424 bytes - 42723a4e - file date is 4/29/2005 05:44:48
C:\rowan\mig\Rbutton.ocx, loaded at 0x03e80000 - 45056 bytes - 38f5ed83 - file date is 4/13/2000 16:53:40
C:\rowan\mig\RListBox.ocx, loaded at 0x03e90000 - 75264 bytes - 38f5edd9 - file date is 4/13/2000 16:55:06
C:\rowan\mig\RRadio.ocx, loaded at 0x03f50000 - 30720 bytes - 38f5ee70 - file date is 4/13/2000 16:57:36
C:\rowan\mig\RCombo.ocx, loaded at 0x03f60000 - 36352 bytes - 38f5ede0 - file date is 4/13/2000 16:55:12
C:\rowan\mig\RTabs.ocx, loaded at 0x03f80000 - 225280 bytes - 38f5ee4b - file date is 4/13/2000 16:57:00
C:\rowan\mig\Redit.ocx, loaded at 0x03fc0000 - 29696 bytes - 38f5edf2 - file date is 4/13/2000 16:55:32
C:\rowan\mig\RStatic.ocx, loaded at 0x03fd0000 - 28672 bytes - 38f5ee3a - file date is 4/13/2000 16:56:42
C:\rowan\mig\REdtBt.ocx, loaded at 0x04230000 - 29184 bytes - 38f5ee03 - file date is 4/13/2000 16:55:48
C:\rowan\mig\Rscrlbar.ocx, loaded at 0x059c0000 - 26624 bytes - 38f5eda8 - file date is 4/13/2000 16:54:16
C:\Rowan\mig\smackw32.dll, loaded at 0x10000000 - 96256 bytes - 357d6111 - file date is 6/9/1998 09:21:36
C:\Rowan\mig\mss32.dll, loaded at 0x20000000 - 269312 bytes - 3558e48e - file date is 5/15/1998 14:49:32
C:\WINDOWS\system32\dplayx.dll, loaded at 0x5ac60000 - 228352 bytes - 44c8eb81 - file date is 5/6/2022 23:16:42
C:\WINDOWS\SYSTEM32\D3DIM.DLL, loaded at 0x5aca0000 - 326656 bytes - 22ee5a5c - file date is 5/6/2022 21:19:58
C:\WINDOWS\SYSTEM32\ResampleDmo.DLL, loaded at 0x5bb00000 - 626488 bytes - 1c09611d - file date is 11/24/2022 18:00:00
C:\WINDOWS\SYSTEM32\msdmo.dll, loaded at 0x5c2e0000 - 33032 bytes - 07765941 - file date is 5/6/2022 21:19:48
C:\WINDOWS\SYSTEM32\DSOUND.DLL, loaded at 0x5c2f0000 - 444928 bytes - b4f6169c - file date is 11/24/2022 17:59:28
C:\Windows\System32\Windows.UI.dll, loaded at 0x5c370000 - 1096488 bytes - e4e1779b - file date is 11/24/2022 17:59:36
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll, loaded at 0x5c480000 - 57840 bytes - bbbd5c5a - file date is 5/6/2022 21:19:52
C:\WINDOWS\SYSTEM32\midimap.dll, loaded at 0x5c490000 - 21504 bytes - 8a3b143c - file date is 5/6/2022 21:19:48
C:\WINDOWS\SYSTEM32\MSACM32.dll, loaded at 0x5c4a0000 - 97088 bytes - adf1fc8c - file date is 5/6/2022 21:19:48
C:\WINDOWS\SYSTEM32\msacm32.drv, loaded at 0x5c4c0000 - 26624 bytes - f68d3fd8 - file date is 5/6/2022 21:19:48
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL, loaded at 0x5c4d0000 - 1605880 bytes - 6f417959 - file date is 12/2/2022 09:08:04
C:\WINDOWS\SYSTEM32\AVRT.dll, loaded at 0x5c660000 - 29944 bytes - 2409bb7c - file date is 11/24/2022 17:59:28
C:\WINDOWS\SYSTEM32\ksuser.dll, loaded at 0x5c920000 - 23744 bytes - 5956aee5 - file date is 5/6/2022 21:19:48
C:\WINDOWS\SYSTEM32\wdmaud.drv, loaded at 0x5c930000 - 220160 bytes - 0b8edbf9 - file date is 5/6/2022 21:19:48
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL, loaded at 0x5c970000 - 495336 bytes - 8b84b59e - file date is 11/24/2022 17:59:28
C:\WINDOWS\SYSTEM32\winmmbase.dll, loaded at 0x5c9f0000 - 117792 bytes - d08c645a - file date is 5/6/2022 21:19:48
C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_42d541138da2ebd2\COMCTL32.DLL, loaded at 0x5ca10000 - 582992 bytes - 3d0b4d09 - file date is 11/24/2022 17:59:28
C:\WINDOWS\SYSTEM32\DCIMAN32.dll, loaded at 0x5cab0000 - 11776 bytes - 6abe36d9 - file date is 11/24/2022 17:59:38
C:\WINDOWS\SYSTEM32\DDRAW.dll, loaded at 0x5cac0000 - 535552 bytes - 3b35861a - file date is 5/6/2022 21:19:58
C:\WINDOWS\SYSTEM32\MSVCIRT.dll, loaded at 0x5cbb0000 - 65536 bytes - 82720468 - file date is 5/6/2022 21:19:52
C:\WINDOWS\SYSTEM32\MFC42.DLL, loaded at 0x5cbd0000 - 1269760 bytes - acc71d71 - file date is 5/6/2022 21:19:52
C:\WINDOWS\SYSTEM32\DINPUT.dll, loaded at 0x5cd10000 - 142336 bytes - ba6016de - file date is 5/6/2022 21:20:20
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll, loaded at 0x5d100000 - 2699248 bytes - 56319826 - file date is 11/24/2022 17:59:32
C:\WINDOWS\SYSTEM32\textinputframework.dll, loaded at 0x5d390000 - 926080 bytes - a05762fd - file date is 12/2/2022 09:08:10
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_b53c057d22ce6f37\igc32.dll, loaded at 0x5d950000 - 49616584 bytes - 6375a3ab - file date is 12/20/2022 18:33:04
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_b53c057d22ce6f37\igdgmm32.dll, loaded at 0x60880000 - 3306152 bytes - 6375a097 - file date is 12/20/2022 18:37:40
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_b53c057d22ce6f37\igd9dxva32.dll, loaded at 0x60bb0000 - 50345384 bytes - 6375a12c - file date is 12/20/2022 18:36:50
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_b53c057d22ce6f37\igdumdim32.dll, loaded at 0x63b50000 - 1540728 bytes - 6375a13e - file date is 12/20/2022 18:38:04
C:\WINDOWS\SYSTEM32\CoreMessaging.dll, loaded at 0x66470000 - 834160 bytes - 485e10fe - file date is 11/24/2022 17:59:36
C:\WINDOWS\SYSTEM32\inputhost.dll, loaded at 0x66540000 - 1337232 bytes - ba2b171f - file date is 11/24/2022 17:59:32
C:\WINDOWS\SYSTEM32\TextShaping.dll, loaded at 0x666d0000 - 610984 bytes - a50f952f - file date is 11/24/2022 17:59:32
C:\WINDOWS\SYSTEM32\HID.DLL, loaded at 0x66c40000 - 27648 bytes - 4bfa8de4 - file date is 5/6/2022 21:19:56
C:\WINDOWS\SYSTEM32\dxcore.dll, loaded at 0x66f60000 - 166336 bytes - 9433f44e - file date is 11/24/2022 17:59:32
C:\WINDOWS\SYSTEM32\dxgi.dll, loaded at 0x67750000 - 817656 bytes - d15ea031 - file date is 12/2/2022 09:08:10
C:\WINDOWS\SYSTEM32\dbghelp.dll, loaded at 0x68170000 - 1793888 bytes - 24bbb7f6 - file date is 5/6/2022 21:19:56
C:\WINDOWS\system32\uxtheme.dll, loaded at 0x6bcb0000 - 500224 bytes - 40762b68 - file date is 12/2/2022 09:08:08
C:\WINDOWS\SYSTEM32\WINMM.dll, loaded at 0x6bf00000 - 189072 bytes - 109d4e2c - file date is 11/24/2022 17:59:28
C:\WINDOWS\SYSTEM32\SspiCli.dll, loaded at 0x6bff0000 - 143592 bytes - 3e8e0ebd - file date is 11/24/2022 17:59:28
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_b53c057d22ce6f37\igdinfo32.dll, loaded at 0x6c660000 - 123456 bytes - 6375a03b - file date is 12/20/2022 18:37:44
C:\Program Files\Avast Software\Avast\x86\aswhook.dll, loaded at 0x6c880000 - 67480 bytes - 63864b65 - file date is 12/12/2022 11:15:32
C:\WINDOWS\SYSTEM32\DEVOBJ.dll, loaded at 0x6ccc0000 - 163728 bytes - 9576c42b - file date is 11/24/2022 17:59:36
C:\WINDOWS\SYSTEM32\UMPDC.dll, loaded at 0x71100000 - 51632 bytes - 2f1c04f9 - file date is 5/6/2022 21:19:54
C:\WINDOWS\SYSTEM32\powrprof.dll, loaded at 0x71110000 - 277400 bytes - 0c32a414 - file date is 12/2/2022 09:08:12
C:\WINDOWS\SYSTEM32\wintypes.dll, loaded at 0x71380000 - 815040 bytes - 4b073bac - file date is 12/2/2022 09:08:12
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL, loaded at 0x72730000 - 33144 bytes - be07fe51 - file date is 5/6/2022 21:19:50
C:\WINDOWS\SYSTEM32\MSASN1.dll, loaded at 0x73ba0000 - 52176 bytes - 5ecfee38 - file date is 11/24/2022 17:59:36
C:\WINDOWS\SYSTEM32\kernel.appcore.dll, loaded at 0x74460000 - 69752 bytes - b9bba47a - file date is 5/6/2022 21:19:54
C:\WINDOWS\SYSTEM32\cfgmgr32.dll, loaded at 0x74b00000 - 246336 bytes - 30bf23e0 - file date is 11/24/2022 17:59:36
C:\WINDOWS\System32\msvcrt.dll, loaded at 0x74ba0000 - 797464 bytes - f8ef3607 - file date is 11/24/2022 17:59:28
C:\WINDOWS\System32\KERNEL32.DLL, loaded at 0x74c70000 - 674904 bytes - f5cd78ad - file date is 12/13/2022 20:45:24
C:\WINDOWS\System32\coml2.dll, loaded at 0x74d60000 - 384848 bytes - 2e302325 - file date is 5/6/2022 21:19:54
C:\WINDOWS\System32\ucrtbase.dll, loaded at 0x74dc0000 - 1128496 bytes - bbf7fb0e - file date is 11/24/2022 17:59:36
C:\WINDOWS\System32\KERNELBASE.dll, loaded at 0x74fd0000 - 2540176 bytes - d511e791 - file date is 12/13/2022 20:45:20
C:\WINDOWS\System32\combase.dll, loaded at 0x75240000 - 2618088 bytes - 560ada32 - file date is 12/2/2022 09:08:12
C:\WINDOWS\System32\CRYPT32.dll, loaded at 0x754d0000 - 1051104 bytes - 2fcd4473 - file date is 11/24/2022 17:59:36
C:\WINDOWS\System32\WINTRUST.dll, loaded at 0x755e0000 - 351256 bytes - 331aa177 - file date is 12/2/2022 09:08:10
C:\WINDOWS\System32\shcore.dll, loaded at 0x75640000 - 786656 bytes - 84ce03ec - file date is 12/2/2022 09:08:12
C:\WINDOWS\System32\bcryptPrimitives.dll, loaded at 0x75700000 - 398768 bytes - 364e9745 - file date is 5/6/2022 21:19:36
C:\WINDOWS\System32\win32u.dll, loaded at 0x75770000 - 103288 bytes - 51555876 - file date is 11/24/2022 17:59:34
C:\WINDOWS\System32\PSAPI.DLL, loaded at 0x75790000 - 18080 bytes - 7b53235d - file date is 5/6/2022 21:19:56
C:\WINDOWS\System32\sechost.dll, loaded at 0x75860000 - 529432 bytes - 45764b57 - file date is 11/24/2022 17:59:28
C:\WINDOWS\System32\SHELL32.dll, loaded at 0x758f0000 - 6723256 bytes - cc1dafd8 - file date is 12/2/2022 09:08:08
C:\WINDOWS\System32\IMM32.DLL, loaded at 0x75f60000 - 149784 bytes - 1d98d784 - file date is 11/24/2022 17:59:38
C:\WINDOWS\System32\GDI32.dll, loaded at 0x75f90000 - 132208 bytes - 7c0e7849 - file date is 11/24/2022 17:59:32
C:\WINDOWS\System32\msvcp_win.dll, loaded at 0x75fc0000 - 492208 bytes - b3cabdd0 - file date is 11/24/2022 17:59:36
C:\WINDOWS\System32\ADVAPI32.dll, loaded at 0x761c0000 - 502544 bytes - 3e9ef803 - file date is 11/24/2022 17:59:28
C:\WINDOWS\System32\RPCRT4.dll, loaded at 0x76240000 - 761288 bytes - ced69859 - file date is 5/6/2022 21:19:50
C:\WINDOWS\System32\USER32.dll, loaded at 0x76300000 - 1731272 bytes - 970a5917 - file date is 12/2/2022 09:08:12
C:\WINDOWS\System32\IMAGEHLP.dll, loaded at 0x764b0000 - 101752 bytes - 55ee5d1f - file date is 5/6/2022 21:19:36
C:\WINDOWS\System32\SETUPAPI.dll, loaded at 0x764d0000 - 4497160 bytes - 7bfb87da - file date is 11/24/2022 17:59:38
C:\WINDOWS\System32\gdi32full.dll, loaded at 0x76920000 - 899200 bytes - 3c66ddc5 - file date is 12/13/2022 20:45:26
C:\WINDOWS\System32\MSCTF.dll, loaded at 0x76a60000 - 890424 bytes - 9ac92f6a - file date is 11/24/2022 17:59:30
C:\WINDOWS\System32\OLEAUT32.dll, loaded at 0x76b40000 - 631696 bytes - 5668be81 - file date is 11/24/2022 17:59:36
C:\WINDOWS\System32\ole32.dll, loaded at 0x76be0000 - 1368192 bytes - a4fa34e5 - file date is 11/24/2022 17:59:36
C:\WINDOWS\System32\clbcatq.dll, loaded at 0x76d30000 - 542816 bytes - 0f10fd5a - file date is 11/24/2022 17:59:36
C:\WINDOWS\SYSTEM32\ntdll.dll, loaded at 0x76e80000 - 1747904 bytes - 722d9f42 - file date is 12/2/

**Comment by narzoul** [comment]
I remember this game has a buffer overflow issue if there are too many display modes supported by the monitor. You need to narrow down the list with the SupportedResolutions setting. Try putting this in DDrawCompat.ini:
`SupportedResolutions=640x480,800x600,1024x768`

@witchiewoman Based on your debug logs, this definitely seems to be the issue for you.

@WesCov If this doesn't work for you, please upload debug logs next time! You can enable debug logging in the Release build too by putting LogLevel=debug in DDrawCompat.ini.

**Comment by witchiewoman** [comment]
Ok that helped can even gt into preferences menus now but when I hit fly i CTD's with this log on 4.0

[DDrawCompat-Mig.log](https://github.com/narzoul/DDrawCompat/files/10348029/DDrawCompat-Mig.log)

**Comment by narzoul** [comment]
Could you try it a few more times, does it always crash? I also had a random crash there when I tried it earlier today, but it worked fine on second try. When I looked at the crash dump and the logs I didn't see anything DirectX related, so I assumed it was another random unrelated crash (most probably memory corruption). I don't see anything strange at the end of your logs either.

**Comment by WesCov** [comment]
Supplying the SupportedResolutions ini line fixed all the issues for me.  No crashes and with the bdg patch applied I can use a flight stick.  Thank you so much!  And thank you @witchiewoman for your input!  I hope your issues can be resolved as easily.  Do try to turn off the intro video in bdg.txt because I think that does cause some problems.

**Comment by witchiewoman** [comment]
Continues to crash to desktop when I hit frag. Videos were disabled already.

**Comment by witchiewoman** [comment]
[DDrawCompat-Mig.zip](https://github.com/narzoul/DDrawCompat/files/10348548/DDrawCompat-Mig.zip)

**Comment by witchiewoman** [comment]
crash log

[crashlog.txt](https://github.com/narzoul/DDrawCompat/files/10348641/crashlog.txt)

**Comment by narzoul** [comment]
Please collect a crash dump too as described here: https://github.com/narzoul/DDrawCompat/issues/50#issuecomment-520162844
Attach it together with the debug logs from the same run. Thanks!

**Comment by narzoul** [comment]
After comparing our logs, I just realized we have different in-game settings. I forgot to max out the graphics. Now I can reproduce the crash. I think it's caused by the trilinear filtering. Try using bilinear only and it should work.

**Comment by witchiewoman** [comment]
Works! Thanks!

**Comment by narzoul** [comment]
Ok, I found the reason for the crash, or at least in my case. When palettized textures are supported, the "trilinear" and "all" filters try to create mipmapped palettized textures, which is not currently implemented in DDrawCompat's palettized texture emulation (it doesn't yet support mipmaps).

Setting PalettizedTextures=off in DDrawCompat.ini allows me to use the "trilinear" and "all" filters too without a crash. Although I'm not completely sure if it'll help in your case also, because your log's a bit different. But it's worth a try.

**Comment by WesCov** [comment]
Thanks!
