### ISSUE TITLE
Napoleon in Italy black boxes instead of sprites

### ISSUE THREAD

**Issue by Buechnerstod** [narzoul/DDrawCompat#177]
hI
I have had problems running Napoleon in Italy (created by Hussar Games, published through Matrxi Games - though no discontinued) 
DDRAWcompat has made the game screen usable again, but on the game map all the uni sprites are black boxes and if you move the screen around the sprites seem to be on some black layer within the black boxes, but out of all alignment with where the sprites should be 
![Untitled-1](https://user-images.githubusercontent.com/121831921/210281101-75f03e29-7d14-4355-9e70-bf845f7f3153.jpg)

**Comment by narzoul** [comment]
I don't have this game so it'll be hard to debug. Do any of the other Hussar Games have similar issues for you? They seem to use similar engines at least, but I didn't have any problems like this with either 1848 or the For Liberty demo.

**Comment by Buechnerstod** [comment]
yes they all use the same engine and i get teh problem with all of them.
the only fix for me is to run them in vmware virtual xp os it seems

**Comment by narzoul** [comment]
Hmm, I have somewhat similar glitches in 1848 only if I enable ForceD3D9On12. Do you have an Intel GPU that uses D3D9On12 perhaps? Please share your DDrawCompat log file, it can be seen there.

**Comment by narzoul** [comment]
I don't see it. Please reply via GitHub, I think e-mail attachments are ignored.

**Comment by Buechnerstod** [comment]
[DDrawCompat-Napoleon[2].log](https://github.com/narzoul/DDrawCompat/files/10342774/DDrawCompat-Napoleon.2.log)


okay here it is

**Comment by narzoul** [comment]
Yes, your system is using D3D9On12, so that probably causes most of your issues. Compatibility with D3D9On12 is not yet great in DDrawCompat. I've started improving on it recently, and it looks like this game already displays fine already with my offline development version. I'll try to identify which fixes are needed and get you a testable release tonight.

**Comment by Buechnerstod** [comment]
thats great thank you

so this d3d9on12 thing is there anything i can do to  not have my system use it? it might explain some other graphics issues i am having which others do not seem to be 

also this might what is causing Battalia in my other post here to have issues too then?

**Comment by narzoul** [comment]
Yes, it's probably the same reason for your issues in other games, but I haven't had time to check those yet. Based on your posts in DxWnd forums I suppose you have a laptop with NVIDIA Optimus, but unfortunately it doesn't support running DX1-8 on the NVIDIA GPU under Windows 10/11, so you're stuck with the integrated Intel GPU for those (unless you use something like dgVoodoo 2 which translates to DX11/12). See here:
https://nvidia.custhelp.com/app/answers/detail/a_id/3733/~/games-based-on-directx-8-and-older-versions-of-directx-will-only-run-on

And newer Intel GPUs are stuck with D3D9On12 because they don't have a native DirectX 9 driver anymore. See here:
https://www.intel.com/content/www/us/en/support/articles/000091238/graphics.html

**Comment by Buechnerstod** [comment]
oh damn - thank you for enlightening me on this, - i did see the word optimus come up in some nvidia control panel settings
so really even if i downgraded to windows10 i would still have these issues then? it seems unavoidable if that is how they are making gaming laptops now? or are their brands which will still run dx1-8 on nvidia or some equivalent amd thing?

fortunately my biggest area of retro gaming is with dosbox still, but there are a host of late 90s early 00s games i still love and play -getting napoleon in italy and battalia workign with ddrawcompat would be sublime

after that, i have to try and see if i can get the ea F1 games to work, - f12000 does so far,

also i am hoping Panzer Commander and Luftwaffe Commander will still work

**Comment by narzoul** [comment]
This simple fix should work for this game (and probably most 2D games in general):
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/10347367/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/10347368/diff.txt) compared to v0.4.0)

This won't help with Battalia, it seems to have a different issue, even without D3D9On12. I'll look into it later.

I think the GDI resource leak fix may be needed too (in case you notice the cursor turning into a black box eventually), but it can be worked around by using DisplayResolution=app if that's the case.

Alt-tabbing is broken as well, but that seems to be partly the game's fault, it doesn't work well with native ddraw either.

**Comment by Buechnerstod** [comment]
yes, Napoleon in Italy looks to be running perfectly now and i suspect it will be the same for For Liberty too! this is great news thank you
