### ISSUE TITLE
Battalia blue boxes round sprites

### ISSUE THREAD

**Issue by Buechnerstod** [narzoul/DDrawCompat#180]
Hi
another wargame - this time an obscure one from 2001 Battalia -https://archive.org/details/wargamer-depot_battalia

in the main 3d game screen the sprites all have their horrible blue boxes around them

if i dont use DDrawcompat the game freezes and crashes, so at least ddrawcompat can help here, just now if you could tell me how i could get rid of the blue boxes that would be good
this is the log - hopefully you can help with this one - perhaps the blue box issue is like what i am getting for Napoleon in Italy
[DDrawCompat-Battalia.log](https://github.com/narzoul/DDrawCompat/files/10341245/DDrawCompat-Battalia.log)

**Comment by Buechnerstod** [comment]
this is what the blue boxes issue i mean, looks like.  - if i use dgvoodoo instead of ddrawcompat, it removes teh blue box problem but it runs incredibly slowly and i cannot seem to do anything about that
![Untitled-2](https://user-images.githubusercontent.com/121831921/210529815-24f97352-3712-4a08-80fb-36f4e7e91273.jpg)

**Comment by Buechnerstod** [comment]
interestingly if i instead use wineD3D (just putting wined3d.dll and ddraw.dll into the game folder) it gets rid of the blue box issue, but the ground texture is instead missing, all turned white

lol, why oh why cant a fix just fix all the things and not just one thing and then break another!

**Comment by Buechnerstod** [comment]
hi -do you think you will be able to find the solution of how to remvoe teh ugly sprite boxes for this title?

**Comment by narzoul** [comment]
Well, I found the problem with color keying in DDrawCompat, but it only fixes normal drivers, it has no effect on D3D9On12 still, and I don't know why. It might be a bug in D3D9On12. Also, part of the ground near the camera is invisible, which is another problem that only happens with D3D9On12, I haven't had time to investigate that yet.

**Comment by Buechnerstod** [comment]
thanks for that - can i get the ddraw.dll with teh fix for the normal
drivers because i put battalia on a virtual winxp and it runs but also has
the color sprite box issue there too

**Comment by narzoul** [comment]
DDrawCompat doesn't work in XP, nor does it support virtual environments. It requires WDDM drivers to begin with, which XP doesn't support. The fix itself is also in the WDDM part.

**Comment by Buechnerstod** [comment]
hi Narzoul - any chance you can still investigate why there is the issue with d3d9on12 drivers for the color key issue?

**Comment by narzoul** [comment]
Well, after looking into the code of D3D9On12, I'm pretty convinced texture color keying is not completely implemented, and in its current state apparently it doesn't work at all. I wouldn't hold my breath until they fix it, since texture color keying was removed in DX8 as a feature, and they don't seem to be fixing any DX8 and older API issues for now. I think their focus is on DX9 only. Maybe it will change in the future.

I started to look into workarounds for it in DDrawCompat, but it's a lot of effort to implement, so it's going slowly. I'm not sure if I'll release a "demo" of it at all before the next release, which at the current rate may still be months away.

**Comment by Buechnerstod** [comment]
Ok, thanks for the update. that is okay, i will just wait.

**Comment by Buechnerstod** [comment]
okay i found a great fix for Battalia at last - aqrits DDraw wrapper - http://bitpatch.com/ddwrapper.html

posting herre just in case perhaps you can see what his wrapper does-. in the aqrit.cfg i have this setup

RealDDrawPath            = AUTO
BltMirror                = 0
BltNoTearing             = 0
ColorFix                 = 0
DisableHighDpiScaling    = 0
FakeVsync                = 1
FakeVsyncInterval        = 0
ForceBltNoTearing        = 0
ForceDirectDrawEmulation = 1
NoVideoMemory            = 1
SingleProcAffinity       = 0
ShowFPS                  = 0

**Comment by narzoul** [comment]
ForceDirectDrawEmulation disables hardware acceleration, which probably forces the game to use software rendering, thus bypassing the D3D9On12 rendering issues. You can do the same with Microsoft Application Compatibility Toolkit, the shim is also called ForceDirectDrawEmulation.

DDrawCompat doesn't support it though and will disable the shim, because it used to cause issues with its hooks a long time ago. I'm not sure if it would still be the case though. I will revisit it.

**Comment by narzoul** [comment]
I was able to fix the color key issues. No idea about the partially invisible terrain near the camera. It's possible that only the D3D9On12 devs will be able to fix that, I gave up trying for now.

**Comment by narzoul** [comment]
All issues should be fixed in v0.5.2 now since the new igd9trinity32.dll driver appears to render the terrain also correctly.

**Comment by Buechnerstod** [comment]
hi thats great, but how do i get the  igd9trinity32.dll driver - where does that come from?
