### ISSUE TITLE
The Sting! - vsync not working

### ISSUE THREAD

**Issue by Mitch037** [narzoul/DDrawCompat#183]
I've just tested [The Sting!](https://www.mobygames.com/game/windows/sting) with the latest version of DDrawCompat (for Windows 7 x64) linked [HERE](https://github.com/narzoul/DDrawCompat/issues/149#issuecomment-1271986474).
Apparently Vsync doesn't work. I get 120fps in-game. I also tried DDrawCompat.ini with vsync=on but with no success.

**Comment by narzoul** [comment]
What do you mean it doesn't work? Do you see screen tearing?

**Comment by Mitch037** [comment]
I usually get 60fps with Vsync on but in this game I can get as much as 120. I don't get screen tearing. Any idea how to cap fps? Settings MaxFrameRate and/or Vsync via Nvidia Control Panel doesn't do anything.

**Comment by narzoul** [comment]
It seems to me that DDrawCompat's VSync setting should work fine for this game. You can try it via the config overlay too. Press shift+f11 in-game. See the wiki for details. If you adjust the VSync interval parameter higher, it will give you even lower frame rates. You can also use any of the FpsLimiter settings (you can try them from the overlay as well), they also seem to be working fine.

The problem is probably that whatever tool you're using to measure FPS is giving false numbers. I know some of them will usually show twice the actual FPS with DDrawCompat. It's probably caused by hooking incompatibilities. Note that 3rd party tools like that are not supported, so it's not going to be fixed. Instead in the next release I will add some proper FPS counter to DDrawCompat itself. For now, I verified that the actual in-game FPS is exactly what it should be with the configured VSync or FpsLimiter setting, 3rd party tools are just measuring it incorrectly.

**Comment by Mitch037** [comment]
The only application that can display framerate for this game is FRAPS. RTSS doesn't work with it.
If you could add FPS counter to DDrawCompat then it would be great!

**Comment by narzoul** [comment]
A stats overlay was added in v0.5.0, configurable through the [Stats*](https://github.com/narzoul/DDrawCompat/wiki/Configuration#statsaggregatetime) settings. Now you can see that VSync was always working, I assume only FRAPS was showing wrong numbers.
