### ISSUE TITLE
Can't ALT+TAB in Diablo (1996)

### ISSUE THREAD

**Issue by MacPaiva** [narzoul/DDrawCompat#186]
When I use DDRAWCompat latest version with Diablo (1996), I can't ALT+TAB from the game. Is this a normal behavior?

**Comment by MacPaiva** [comment]
Oh, I don't know if with older versions it is possible to use the alt + tab, I just wanted to clarify that I had this using the latest version. About Diablo version, I'm also using a retail CD with the game patched to latest version (1.09b I think). Here's my DDRawCompat log file. Thanks for the help!
[DDrawCompat-Diablo.log](https://github.com/narzoul/DDrawCompat/files/10393496/DDrawCompat-Diablo.log)

**Comment by narzoul** [comment]
Hmm, strange, after upgrading to 1.09b, I can't alt-tab either. I think it has something to do with the IgnoreAltTab shim applied from Microsoft's compatibility database:
![diablo_compat](https://user-images.githubusercontent.com/16432233/211842847-84967aff-e01b-4a37-854c-05db0f27bfda.png)

DDrawCompat is supposed to work around that, I will look into why it doesn't work later. I'm also unsure why it works with the unpatched (1.0) version.

As a workaround, you can try renaming Diablo.exe to something else, so that the IgnoreAltTab shim doesn't get applied.

**Comment by MacPaiva** [comment]
Awesome! Thank you!

**Comment by narzoul** [comment]
I checked it out and the problem is caused by the game loading ddraw dynamically after the compatibility setting already installed its keyboard hook to block alt+tab, so DDrawCompat can't stop it from installing. I don't know of a clean way to remove it afterwards, but I might try some ideas later.
