### ISSUE TITLE
Couldn't load all setting.ini

### ISSUE THREAD

**Issue by godking232** [narzoul/DDrawCompat#188]
hi,when i use shift+f11 in the game ,the menu just show a little settings ,just like below
AlternatePixelCenter = on
BltFilter = bilinear
/# Antialiasing = off
DisplayFilter = bilinear(14)
/# FontAntialiasing = app
/# FpsLimiter = off
/# RenderColorDepth = app
ResolutionScale = app(4)
ResolutionScaleFilter = bilinear
/# SpriteDetection = off
/# SpriteFilter = app
/# SpriteTexCoord = app
/# TextureFilter = app
/# VSync = app
why not show the others,just like "SoftwareDevice" eg.

appreciately

**Comment by narzoul** [comment]
Settings like SoftwareDevice are not shown because they would require an application restart to take effect anyway. The overlay only shows settings that can be changed without restarting the application, and that have an immediately visible effect, in order to allow previewing those settings in-game.

**Comment by godking232** [comment]
got it  tks
