### ISSUE TITLE
Color Issue with Deer Hunter II

### ISSUE THREAD

**Issue by CarstenK1991** [narzoul/DDrawCompat#19]
Hey, I recently tried the wrapper with Deer Hunter II and the game itself runs buttery smooth except the menu and user Interface colors are all messed up. As you can see the initial title screen (except for the cursor) and the actual ingame environments look fine but the rest seems to have some kind of pallette problem...

Happens with the latest experimental release as well as the stable ones. I'm running the game on a laptop with Intel HD Graphics.

I'm really enjoying your work, it'd be great if you could take a look at it :)

![1](https://user-images.githubusercontent.com/29836318/29232598-c11a63bc-7eec-11e7-812a-201d29045d68.JPG)
![2](https://user-images.githubusercontent.com/29836318/29232597-c116c202-7eec-11e7-9a10-441b63261265.JPG)
![3](https://user-images.githubusercontent.com/29836318/29232599-c11f6aa6-7eec-11e7-976a-de78bb25811c.JPG)

**Comment by narzoul** [comment]
I can reproduce the problem with the Demo version, but only in Software Renderer mode. You should try playing the game with the hardware renderer while I investigate and try to fix it.

I'm not sure if the full version is set up the same way, but in the demo you can run DH2Config.exe, click "Advanced Configuration Options", "Graphics" tab, and change "Software Rendering" to "display" (or whatever else is there) to enable hardware rendering. It uses 16 bit color instead of 8 bit so it doesn't have any palette issues.

**Comment by narzoul** [comment]
Fixed in latest experimental release.
