### ISSUE TITLE
Gorasul 1.06 crashes when starting the game

### ISSUE THREAD

**Issue by Felipefpl** [narzoul/DDrawCompat#190]
I'm using DDrawCompat 0.40 to get rid of mouse slowdown and the game crashes right at the beginning, this doesnt happen when the ddraw.dll isnt there.

https://www.myabandonware.com/game/gorasul-the-legacy-of-the-dragon-eor

Edit - i tested and confirmed that 0.3.1 works fine.

**Comment by narzoul** [comment]
I don't have a crash at the start. I can start a new game just fine. Well, almost just fine, since the main menu is just a lot of cursor trails, with the menu items only popping up if you mouse over them. But after starting the game, everything looks fine.
Could you share debug logs from DDrawCompat v0.4.0 with the crash?

**Comment by Felipefpl** [comment]
Thanks for the tip about WinXP, here is the debug log of gorasul.

[DDrawCompat-gorasul.zip](https://github.com/narzoul/DDrawCompat/files/10482755/DDrawCompat-gorasul.zip)

**Comment by narzoul** [comment]
Hmm, it looks similar to one of the Windows 7 crashes I debugged a while ago.
Please try the test version attached here: https://github.com/narzoul/DDrawCompat/issues/149#issuecomment-1271986474

**Comment by Felipefpl** [comment]
I downloaded the last file attached and it worked! The crash is gone but the screen size was reduced a big with horizontal black bars on left/right side of the screen, too bad i cant show a pic. i used print screen but cant show anything aside a black picture. Thank you for your help. The crash fix will be in 0.4.1?

**Comment by narzoul** [comment]
I don't think there will be a v0.4.1 anymore, more likely v0.5.0, but the crash fix will be there, yes.

You can use DisplayResolution=app to let your GPU driver or monitor do the display scaling instead of DDrawCompat, if you prefer to have a horizontally stretched screen without black bars. Check the [Configuration wiki](https://github.com/narzoul/DDrawCompat/wiki/Configuration).
The next version will also have a setting to scale to full screen if you want to use DDrawCompat's display scaling.

**Comment by Felipefpl** [comment]
I see, that's nice. :)

Thanks for everything. :+1:

**Comment by narzoul** [comment]
The crash fix was added in v0.5.0, and you can now use the [DisplayAspectRatio](https://github.com/narzoul/DDrawCompat/wiki/Configuration#displayaspectratio) setting to stretch the image to the full screen.
