### ISSUE TITLE
Ubisoft F1 Racing Simulation crash upon race start

### ISSUE THREAD

**Issue by Buechnerstod** [narzoul/DDrawCompat#202]
I have been trying alot of options with this game, well all the usual options that is - dxwnd, dgvoodoo, dgvoodoo + dxwnd, and even just dgvoodoo+native nvidia cpl
and of course ddraw compat

all the options have some issue in some way, the most annoying though is either the unplayable fastness of i run it natively using my nvidia card,  or the extreme slowness if i try dxwnd or dgvoodoo

If i try Ddrawcompat, everything starts right (i switched off vsysnc  for it) and when a race loads the game graphics look to be moving at the right speed while the starting grid is shown, but as soon as i go into the cockpit to start the race, then the screen freezes, and it soon crashes - the screen doesnt refresh right from the starting grid intro and hte driver cockpit then appears over this but it is all frozen and a CTD soon occurs. One has to then close hte game exe from task manager. - the game crashes to desktop but the game exe is still open so one has to close via task manager.

if there could be a way to run the game with Ddrawcompat it might be possibly perfect and playable at last!

**Comment by narzoul** [comment]
Is this with D3D9On12 again? Because the game seems to run fine with native AMD display driver for me. I do get a frozen screen with D3D9On12 in the cockpit, but that's already fixed in my offline development version. So in that case, you'll just have to wait for the next release (no ETA).

Other than that, the only issue I noticed is that the game doesn't exit properly, and has to be terminated via Task Manager, but that seems to be the case without DDrawCompat too. I don't think it's a ddraw issue.

**Comment by Buechnerstod** [comment]
Well I guess it must be a d3d9on12 issue then, going by what you describe.
Unfortunately I don't have an AMD card to try things on, just the Intel UHD
card and the NVIDIA rtx Optimus cards on my gaming laptop

I would have assumed on my PC that the NVIDIA card simply wouldn't work for
such an older game though, yet it seems to do so of I select that card
which surprised me, but in any case I get that frozen cockpit crash

I will eagerly await the update then

In the meantime there is that other wrapper I haven't tried yet - wined3d
so I will see if that will do anything favorable

**Comment by narzoul** [comment]
Should be fixed in v0.5.0. Let me know if there are still issues.
