### ISSUE TITLE
Shifted menu colors in Claw (1997)

### ISSUE THREAD

**Issue by PlayNeth** [narzoul/DDrawCompat#207]
Something obscure I stumbled upon while trying out custom levels:
![image](https://user-images.githubusercontent.com/82559127/219876798-7e4d69a8-d0f5-4a96-9985-4027966140e1.png)
While this is how it should look:
![image](https://user-images.githubusercontent.com/82559127/219876969-af4eeada-c0ae-4c40-9400-f6ab8501fb42.png)
Curious what the issue might be, never seen something like this before.
Tested using the latest version of ddrawcompat.

**Comment by narzoul** [comment]
Actually, the first picture is closer to what it should look like. The game is running in 8-bit (256 colors) exclusive fullscreen mode, so it's allowed to override the 20 static colors that GDI uses for rendering window elements. DWM doesn't respect this and just renders everything in the desktop's color depth, which is usually 32-bits. I'm not sure what it does in Windows 7 if the desktop is set to 8-bit color mode. The game crashes in my Win7 VM so I could only try it in an XP one:
![claw-xp-classic](https://user-images.githubusercontent.com/16432233/219899219-7b23e57c-11e8-4631-91aa-0f33bedeefa8.png)

The only difference compared to DDrawCompat is that different colors get assigned to the static colors. This might be because DDrawCompat doesn't emulate some palette modifying operations 100% accurately, but it doesn't really matter for this game, because it doesn't preserve the static entries either way, so it's never going to look "right".

This "bug" only affects the CrazyHook modded version of the game btw, the official game versions render the dialog with proper colors. I'm guessing the mod was made for newer systems and wasn't tested on a pre-DWM system.

**Comment by PlayNeth** [comment]
Fascinating. Had no idea that was a thing exclusive to the crazyhook version. Thanks for the info!
