### ISSUE TITLE
RollerCoaster Tycoon Deluxe: Can't see file select windows

### ISSUE THREAD

**Issue by OpenRift412** [narzoul/DDrawCompat#225]
In the original Rollercoaster Tycoon, there seems to be an issue where file selection windows don't show when saving or loading a game, as well as other places where file selection is required. Instead it just freezes the game until you press escape, which closes what I assume is the invisible file select window. The thing is though, this functionality works perfectly fine in RCT2. Is there a certain setting I should have set for RCT1 for these dialogues to show?

Here's what they look like in RCT2 for context. It essentially minimizes the main window while the file selection prompt shows up.
![image](https://user-images.githubusercontent.com/29780788/235489865-30b108be-f5e9-4836-b7a5-f241214b43d3.png)

**Comment by OpenRift412** [comment]
Here's a log of me loading up the game and attempting to load a saved game. Don't know if this will be much help but I might as well include it.
[DDrawCompat-RCT.log](https://github.com/narzoul/DDrawCompat/files/11366834/DDrawCompat-RCT.log)

**Comment by narzoul** [comment]
The game uses an unusual combination of flags when calling SetCooperativeLevel before displaying those dialogs: DDSCL_FULLSCREEN | DDSCL_NORMAL. This was confusing DDrawCompat, which thought the game remained in fullscreen mode after this, but it actually switches to windowed mode.

It's a little strange that the runtime even allows this, because according to the SDK, this combination should be invalid:
> DDSCL_NORMAL 
The application functions as a regular Microsoft® Windows® application. This flag cannot be used with the DDSCL_ALLOWMODEX, DDSCL_EXCLUSIVE, or DDSCL_FULLSCREEN flags. 

Anyway, I made a quick fix: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/11471983/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/11471984/diff.txt) compared to v0.4.0)

**Comment by OpenRift412** [comment]
Nice, thanks! I'll test this one out!

**Comment by OpenRift412** [comment]
Seems like to works pretty good. Though it does seem to be affected by Windows' interface scaling, which can sometimes result in windows being 25% bigger than it would be at 100% scaling meaning they can be bigger than the actual screen. Don't know if there's a way to make that independent of System scaling (I tried messing with DpiAwareness but it didn't seem to help), but that may be something else that's worth looking into.

**Comment by narzoul** [comment]
The invisible dialog windows are fixed in v0.5.0. Also, using DpiAwareness=unaware should fix the oversized dialogs now. Make sure to remove high DPI scaling overrides from the executable first (or set it to "system" there), as mentioned in the wiki too.
