### ISSUE TITLE
Hooligans Storm Over Europe

### ISSUE THREAD

**Issue by HooliganStorm** [narzoul/DDrawCompat#229]
I am trying to play Hooligans Storm Over Europe on windows 10.

I have tried 4 different things so far including virtual machines, adding this file to the hooligans game file has got me the furthest so far but unfortunately the menu works then as soon as the mission starts to load it crashes the game back out which was so frustrating after finally getting the game to play. 

Any advice or help would be much appreciated.

**Comment by narzoul** [comment]
At least in my case, the game crashes when pressing the Rumble button under Season in the main menu, because of missing Indeo Video 5.0 codec support. The codec is still available on Windows 10+, but disabled by default. You can restore it by downloading and executing the iv50_x64.reg file (for 64-bit Windows) or the iv50_x86.reg file (for 32-bit Windows):
https://community.pcgamingwiki.com/files/file/2493-indeo-codec-restoration-patch-for-windows-10/

If you're not sure if your Windows is 32-bit or 64-bit, then applying both fixes should be fine.

After this, the game seems to work well on my end. If it still doesn't work for you, please enable LogLevel=debug in DDrawCompat.ini, and attach your DDrawCompat-hooligans.log file after the crash.

**Comment by narzoul** [comment]
The videos should be working now without external fixes too in DDrawCompat v0.5.0.
