### ISSUE TITLE
C&C Tiberian Sun Black Screen issue on windows 10

### ISSUE THREAD

**Issue by FunkyFr3sh** [narzoul/DDrawCompat#23]
Title says it all, couldn't do any more testing since I can't see the menus.

Tested with the freeware release OfficialCnCTiberianSun.rar

Can be downloaded from here:
https://cncnz.com/features/freeware-classic-command-conquer-games/

**Comment by narzoul** [comment]
Could this be the same issue that was already reported and fixed in issue #15? Did you check with the latest experimental release?

**Comment by FunkyFr3sh** [comment]
With the latest experimental release I get a black screen, v0.2.1 gives me a unable to set video mode error and the game doesn't start up.

"DXPrimaryEmulation -DisableMaxWindowedMode" with the app compat toolkit works


Should I try what you suggested or was that included in the latest release? "Replace g_frontBuffer with g_backBuffer"

**Comment by narzoul** [comment]
No, that one is already included in the latest experimental release. The game works fine on my end currently.
Do you have the latest "Fall Creators Update" for Windows 10 installed already? I don't have it yet, maybe that's the difference. If you have it, I'll see if I can install it earlier than it would normally roll out here.

Also, make sure you're not running any recording or overlay software, there's a known incompatibility with most of them that hasn't been fixed yet.

**Comment by FunkyFr3sh** [comment]
I don't have the fall creators update yet (still on 1703). Got no recording software running and also made sure GameDVR is disabled completely.

Log says the following:
8472 23:53:36.945 Process path: C:\Spiele\TS\game.exe
8472 23:53:36.945 Environment variable __COMPAT_LAYER = "DetectorsXP"
8472 23:53:36.945 Loading DDrawCompat from C:\Spiele\TS\DDRAW.dll
8472 23:53:36.953 Disabling external hook to DirectDrawCreate in apphelp.dll
8472 23:53:36.953 DDrawCompat loaded successfully
8472 23:53:37.003 Installing registry hooks
8472 23:53:37.004 Installing Direct3D driver hooks
8472 23:53:37.004 Installing DirectDraw hooks
8472 23:53:37.006 Hooking user mode display driver: "igdumd32.dll"
8472 23:53:37.011 Installing Direct3D hooks
8472 23:53:37.014 Installing GDI hooks
8472 23:53:37.018 Installing display mode hooks
8472 23:53:37.018 Finished installing hooks
8472 23:53:37.427 GDI used DC cache size: 1

**Comment by FunkyFr3sh** [comment]
Commented this line out and now it works... (still testing)

D3dDdi::installHooks();

**Comment by narzoul** [comment]
Ok, looks like you're running the game on some integrated Intel GPU. Do you have any other GPUs in your system that you could test? Is it a laptop or desktop PC?

One thing weird to me is that you have "igdumd32.dll" whereas on my system with Intel HD 4000 (also Windows 10) I have "igdumdim32.dll" instead. Is your graphics driver up to date?

Also, if you can, please compile a debug build and upload the log file from that.

**Comment by FunkyFr3sh** [comment]
I don't have any other GPU. It's a small form factor desktop. I got the latest drivers installed.

https://drive.google.com/file/d/0B5by5H1Q2PxENURFaS1xYjB1MDg/view?usp=sharing

**Comment by narzoul** [comment]
Well, the log clearly shows the Blt operation failing inside compatBlt. Since commenting out D3dDdi::installHooks resolves the issue, my most likely guess is that the CpuOptimized flag added to the system memory "fake" primary surface during creation is interfering with the operation somehow. Please try commenting out this line in DeviceFuncs.cpp:
`resourceData->Flags.CpuOptimized = 1;`

If that solves the problem, then please undo that change and try this one too instead, just to check if CpuOptimized works fine when the surface is created in video memory. In Surface.cpp, comment out the entire "if" block that contains this line:
`sysMemDesc.ddsCaps.dwCaps |= DDSCAPS_SYSTEMMEMORY;`

If removing the CpuOptimized flag didn't solve the problem, then please try to narrow it down by commenting out some lines in DeviceFuncs::setCompatVtable. The most likely culprits are pfnBlt, pfnCreateResource, pfnCreateResource2, pfnLock, pfnUnlock. The two CreateResource functions should be removed together. Same goes for Lock and Unlock. If none of those help, try removing all lines in this function.

**Comment by FunkyFr3sh** [comment]
> Please try commenting out this line in DeviceFuncs.cpp:
resourceData->Flags.CpuOptimized = 1;

You were right, this actually worked!



> If that solves the problem, then please undo that change and try this one too instead, just to check if CpuOptimized works fine when the surface is created in video memory. In Surface.cpp, comment out the entire "if" block that contains this line:
sysMemDesc.ddsCaps.dwCaps |= DDSCAPS_SYSTEMMEMORY;

That didn't work, black screen again.

**Comment by narzoul** [comment]
Thanks! I think that line can actually be safely removed now since 2D surfaces were forced into system memory by a later change, so lock performance is no longer an issue there.

However, there is another CpuOptimized flag used in the same function a few lines below that may still cause problems, and it may be more difficult to get rid of. It was mainly used for fixing the menu lag in Rogue Spear. Can you test that too? If you don't have the game, you can use the demo version which can be downloaded e.g. here:
http://www.moddb.com/games/tom-clancys-rainbow-six-rogue-spear/downloads/rainbow-six-rogue-spear-demo

Most GPUs have heavy stuttering when starting a new campaign, especially when the camera images are changing. Please check both with and without the CpuOptimized flag if you can.

**Comment by FunkyFr3sh** [comment]
I tried to start the game first without DDrawCompat and it crashed instantly (And changed my resolution to 640*400, d'oh what a mess!)

It worked fine with DDrawCompat and without anything commented out. 
I commented both lines out and tried it again, couldn't notice any difference (no stuttering).

https://drive.google.com/drive/folders/0B5by5H1Q2PxEN2NyTm9fM3k5UDA?usp=sharing

**Comment by narzoul** [comment]
Thanks again! Looks like the CpuOptimized flag does cause the lock surface creation to fail, but that doesn't have any negative side effects. Since you don't have any performance issues in the menu anyway, I'll leave that part as it is.

I'll push the fix (removing the first CpuOptimized flag) soon.

**Comment by Nucleoprotein** [comment]
I think best thing will be to make such flags customizable from somekind of configuration file, because of some HW/OS configurations such flags may need to be required to fix some issues.

**Comment by narzoul** [comment]
Well, the one I just removed was definitely not needed anymore, because the flag doesn't even make sense on system memory surfaces. It was used before I made the change that moved off-screen plain surfaces to system memory. As far as I know it only really affected some Intel HD drivers where it forced the video memory surface layout into linear format, avoiding a large overhead of converting the surface between its internal (tiled?) format and linear format when locking/unlocking the surface. Maybe it was also used to fix cases where the surface memory pointer was cached by the app (such as Nox) and reusing the cached pointer was problematic. Now with the surface being created in system memory however, neither of these issues remain anymore.

For the other case where it's still used, maybe it would be useful to have it configurable. But if it still causes issues I'd rather just rework that part to use a more generic and less likely to break solution, such as creating the lock surface in system memory instead. My design philosophy is still to keep unnecessary config flags to a minimum as long as there are generic solutions to these problems that should work on any hardware and OS.
