### ISSUE TITLE
Mig Alley CTD with DDrawCompat Version 0.3.1

### ISSUE THREAD

**Issue by TheSilkMan** [narzoul/DDrawCompat#250]
Hi Narzoul, getting this Access violation which results in a CTD when panning around in 3D.  You may view the dumplog using windbg.  I have not used later versions of  DDrawCompat because this one worked so well. 

[dumplog.dmp](https://github.com/narzoul/DDrawCompat/files/13291634/dumplog.dmp)
[DDrawCompat-MigAlley.log](https://github.com/narzoul/DDrawCompat/files/13291635/DDrawCompat-MigAlley.log)
[DDrawCompat-MigAlley[2].log](https://github.com/narzoul/DDrawCompat/files/13291636/DDrawCompat-MigAlley.2.log)
[ddraw.log](https://github.com/narzoul/DDrawCompat/files/13291852/ddraw.log)

**Comment by narzoul** [comment]
Quoting from the readme:

> Only the latest release is supported.

**Comment by TheSilkMan** [comment]
Hi Narzoul, I can't seem to get the latest version to work. It crashes
during loading.

**Comment by TheSilkMan** [comment]
Hi Narzoul, thanks that worked.  I added the additional resolutions I
normally use.  2d is crystal clear but 3D seems to be at a much lower
resolution than selected in the in game menu. Also, I noticed that if the
DisplayFilter setting in the config file doesn't match the in game
setting(e.g., bilinear, trilinear, All), it crashed to desktop. How can I
get the equivalent of trilinear/All to work? Right now, I only see an
option for bilinear(0-7) in
DDrawCompat.

**Comment by narzoul** [comment]
DisplayFilter doesn't have anything to do with texture filtering. It's just a scaling filter used for upscaling or downscaling from the game's resolution to the actual display resolution selected by the DisplayResolution setting.
I think the crash you are having is this issue: https://github.com/narzoul/DDrawCompat/issues/176#issuecomment-1372867706
As it says there, just set PalettizedTextures=off in DDrawCompat.ini, then it won't crash.

The 3D resolution is whatever you selected in game, plus potential upscaling applied by the ResolutionScale setting. Then the final rendered image is scaled using DisplayFilter to match DisplayResolution. DDrawCompat v0.3.1 didn't support display scaling, so it always used your GPU's or monitor's scaling (depending on your GPU driver's settings). Maybe that had a nicer scaling filter. You can use that instead of DisplayFilter by setting DisplayResolution=app in DDrawCompat.ini.

**Comment by TheSilkMan** [comment]
Hi Narzoul, thanks for the reply.
That did the trick. However, the graphics are blurry no matter what
settings I try. With 3.1, the were crisp and clear.  I tried adjusting
things using the overlay(great feauture!), however I just haven't had
success. Any thoughts on that?

Also, any plans to enable mipmaps?

**Comment by narzoul** [comment]
If you're only using the settings I recommended above (SupportedResolutions, DisplayResolution=app and PalettizedTextures=off) and everything else is on default, then it should look the same as in v0.3.1. Maybe you changed some settings in game and forgot to change it back? Have you checked v0.3.1 again to see if it still looks different? Can you post screenshots from both versions?

Unfortunately I can't test this game myself anymore, because it crashes on my system at startup now. I suspect this has something do with the recent Windows 11 23H2 update.

Mipmaps are supported. Only palettized mipmaps aren't, but I'm not aware of any game that needs them, so I don't wanna waste time adding support until there's a proven need.
