### ISSUE TITLE
[feature request] Reshade compatibility?

### ISSUE THREAD

**Issue by BobbyMcJefferson** [narzoul/DDrawCompat#266]
At the moment DDrawCompat doesn't seem to work with Reshade. Other wrappers like DGVoodoo2 seem to work just fine with Reshade. But I have started to prefer DDrawCompat because it tends to be more compatible with certain games. 

I think being able to use this with Reshade would be a great feature to have.

**Comment by EnergyCube** [comment]
ReShade work on `Direct3D 9, Direct3D 10, Direct3D 11, Direct3D 12, OpenGL and Vulkan` but DDrawCompat purpose is to wrap `Direct3D 1-7` to output the same version but by fixing issues in the flyx. This mean that the output of DDrawCompat is simply incompatible with ReShade.
As stated in the readme: `There is no API conversion involved, most of the rendering is still done by the native DirectDraw/Direct3D 1-7`

dgVoodoo don't have the same purpose, it also wrap `Direct3D 3/5/6/7/8/9` but the ouput isn't the same DirectX version, it's a more modern DirectX version, that make for ex. a Direct3D 7 game able to be render with DirectX 12. And since DirectX 12 is supported by ReShade it work.

So what you are asking is simply impossible for DDrawCompat.

**Comment by narzoul** [comment]
It would be nice, but it's technically not feasible. Reshade only supports DX9+. It works with dgVoodoo because that converts everything to the DX11/12 runtimes, but DDrawCompat keeps everything running in the DX7 runtime.

Ah, EnergyCube was a few seconds faster in answering this. :)
