### ISSUE TITLE
WinQuake doesn't detect all resolutions

### ISSUE THREAD

**Issue by iriyap** [narzoul/DDrawCompat#27]
WinQuake is coded to use both build-in and system reported resolutions. The build-in ones max out at 1024x768, while the rest (e.g. 1280x720) should be reported by system. Can't get the game to show all resolutions with DDrawCompat (both with older releases and the one I compiled from source the last night). [DDHack](http://sol.gfxile.net/ddhack/) works however, maybe take a look at how it does this?

You can download Quake Shareware and WinQuake here:
[WinQuake](https://www.quaddicted.com/files/engines/wq100.zip)
[Quake Shareware](https://www.quaddicted.com/files/idgames2/idstuff/quake/quake106.zip) (resource.1 is just an LZH archive, you can open it with WinRAR or 7zip).

There's a lot of technical info in WQREADME.TXT starting at the "Video modes supported in Win95" section.

Thanks again for all your hard work, I've got so many old games up and running with DDrawCompat!

**Comment by narzoul** [comment]
Sorry, I just got around to checking this out.

This isn't an issue with DDrawCompat. It reports every display mode supported by your display, plus 8 and 16 bit color mode variations of them if those aren't natively supported on your system (such as on Windows 8.1 and 10). You can check this with the logs from the ReleaseWithDebugLogs build in the latest experimental release (ddraw-debug.zip file). Search for the "EnumDisplayModes" calls.

The reason that DDHack appears to work better is because it actually doesn't work. :) WinQuake falls back to using DIB mode instead, which apparently supports a different set of resolutions than DirectDraw mode. You can verify this by opening the console in WinQuake (tilde key) and issuing the "vid_describemodes" command, like the readme says.

You will get the same modes natively or with DDrawCompat if you run the game with the "-dibonly" parameter, as in that case it won't use DirectDraw either (e.g. you won't even get a log file from DDrawCompat).
