### ISSUE TITLE
Scroll speed in Sid Meier's Gettysburg!

### ISSUE THREAD

**Issue by pas-de-2** [narzoul/DDrawCompat#281]
Tried getting Gettysburg to run in win10 with the [1.03 and XP compatibility patches](https://web.archive.org/web/20030207150720/http://www.firaxis.com/downloads_allfiles.cfm) applied. Everything renders well, including the FMVs, except the game scrolls way too fast when edge panning. I tried forcing Vsync, the different FpsLimiters, and exclusive FullScreenMode to no avail. Any chance this is something you could fix?

[DDrawCompat-lee.zip](https://github.com/narzoul/DDrawCompat/files/14106189/DDrawCompat-lee.zip)

**Comment by narzoul** [comment]
This game is entirely rendered by GDI. It only seems to use DirectDraw for setting the display mode.

That said, I extended the flipstart/flipend limiters to also detect cases where the screen is updated with a full screen blit, which seems to work well with this game. You can try it out with this patch:
[ddraw.zip](https://github.com/user-attachments/files/17879505/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/17879506/diff.txt) compared to v0.5.4)

I'd recommend using a maximum of flipend(30), maybe even less.

**Comment by pas-de-2** [comment]
It works! Thank you so much 🙏 I went all the way down to flipend(10) and the scroll speed feels right.

This prompted me to try it with the sequel, Antietam!, from Sid Meier's Civil War Collection disc, and it works there as well, but I don't suppose you might know what's going on with the color depth here? 
![SMA](https://github.com/user-attachments/assets/8c6c60f1-2541-4cb6-913f-5525388980dd)
When launching either Antietam or the South Mountain shortcut with DDrawCompat, it looks like the game launches in the wrong color depth for the intro videos, and then once it reaches the main menu it snaps back to a higher color depth, but there are still these red fringes on various UI elements. It's most obvious on the South Mountain main menu background.

If I launch Antietam.exe _without_ DDrawCompat, the intro videos render at the correct color depth, but once it reaches the main menu the red fringing is still there.

I tried messing with reduced color mode compatability settings and DesktopColorDepth to no avail. Btw, this is on Windows 10.

(Let me know if you'd rather I open a separate issue for this)

**Comment by narzoul** [comment]
> If I launch Antietam.exe without DDrawCompat, the intro videos render at the correct color depth, but once it reaches the main menu the red fringing is still there.

First of all, install the v2.0 beta patch:
https://www.moddb.com/games/sid-meiers-gettysburg/downloads/antietam-beta-patch-v2-0
That should fix this issue.

The videos play incorrectly on Windows 7 natively too, which is the last Windows OS that supported proper 8 bit color depth. It seems to me that DDrawCompat emulates this part well enough.
Ironically, it works better on Windows 8+ because they don't properly emulate 8bpp mode, so GDI is actually rendering in 32bpp.

You can patch the executable to run in 32bpp mode natively. After installing the beta patch above, hex edit antietam.exe and replace these bytes:
`6A 08 56 50 E8 E5 78 05 00`
with this:
`6A 20 56 50 E8 E5 78 05 00`
Only the second byte is different.

This also fixes the videos natively on Windows 7, or with DDrawCompat on any supported OS.

**Comment by pas-de-2** [comment]
Hm, I believe this beta patch was intended for the old stand alone version of SMA. It installs an .exe dated 2/11/2000, while the Antietam.exe installed by the Civil War Collection is dated 8/7/2000. If I install the beta patch over it, the South Mountain add-on (launched with the `-campaign 3` argument) no longer works, it just boots to Antietam.

And while your hex edit does fix the startup videos, the game itself still has this weird red fringing along some of the menu sprites:
![SMA2](https://github.com/user-attachments/assets/02e096d7-a8d6-4d1c-8529-1df893868b75)
when it should look like this:
![SMA3](https://github.com/user-attachments/assets/b97d73c6-8543-4918-ad72-e713a537417c)

**Comment by narzoul** [comment]
Ah, you're right. I went by some install instructions which mentioned you could optionally install the beta patch on top of it, but those instructions were pretty poorly written anyway.

This game seems to rely on a bug (or undocumented feature?) in how palette mapping used to work when blitting from a DIB to a display DC, on older OSes that still supported paletted display DCs.

The game creates a logical palette attached to the display DC, which contains 16 of the 20 system colors, but the remaining 4 system colors at indexes 8, 9, 246 and 247 are remapped using the PC_EXPLICIT flag to indexes 8, 9, 245 and 246, respectively. The way PC_EXPLICIT works is that the palette entry doesn't contain an actual RGB color value, but rather just the index of another color from the system palette, stored within the red component.

The game loads the PCX files and assembles the screen contents into DIB sections, with the DIB palette matching the logical palette above. But since a DIB palette cannot store any flags, the PC_EXPLICIT flag is lost, and those 4 palette entries simply become shades of red instead. This explains why in 32-bit color mode the pixels in the DIB with palette index 246 become red when they're copied to a 32-bit display DC.

The strange part is how it works on old OSes. According to an explanation at https://www.compuphase.com/palette.htm, particularly the section titled "From DIB colour table to system palette", the DIB colors would first be matched to the logical palette, and then the mapping between the logical and system palette decides what palette index is written to the destination surface. This mapping causes the source "red" color at index 246 of the DIB palette to be paired with the PC_EXPLICIT color at index 246 of the logical palette. But in the logical palette, this is not supposed to represent the same red color, but rather another color at index 245 of the system palette (which would be close to black in the mentioned main menu background image, for example). Yet for some reason the matching is seemingly done in a "dumb" way, ignoring the PC_EXPLICIT flag in the logical palette and pretending that it's the same red color. I can't find any documentation of this behavior. However, due to this bug/feature, because the logical palette maps 246 to index 245 of the system palette, this red color shifts back to something closer to the expected color. (I say something closer, because in the original PCX file, this color is supposed to be a slightly different dark shade, but since that color doesn't fit into the non-static part of the system palette, it gets this strange remapping to the preceding color instead.)

Long story short, this is not something I intend to fix in DDrawCompat in the near future (if ever). For now, I leave this hack here so you can use the FPS limiter with this game and still get (hopefully) correct colors:
[ddraw.zip](https://github.com/user-attachments/files/17926639/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/17926643/diff.txt) compared to v0.5.4)
It contains the FPS limiter fix from above, along with changing the display color depth to 32-bit (for fixing the movies), and dynamically replacing the PC_EXPLICIT entries in the DIB color tables with the actually referenced ones from the system palette, which should result in more accurate color mapping in this particular game.

The 32-bit display mode fix can also be added to this newer executable with this replacement (but with the above patch this is not necessary):
6A **08** 68 F0 00 00 00 E8 A0 1B FF FF
6A **20** 68 F0 00 00 00 E8 A0 1B FF FF

But without DDrawCompat, this would break the colors that use index 246 again. I suppose the source PCX files could also be patched to avoid using that particular palette index, and just replace it with the previous one. Note that in the PCX files, the relevant pixels to replace would be those using index 236, which should be replaced with 235. (The game offsets the palette indexes by 10 when loading the files to account for the 10 static colors at the beginning of the system palette).

**Comment by pas-de-2** [comment]
You're an actual wizard, man. Thank you so much!

**Comment by narzoul** [comment]
Looks like it might be ClearType or something, have you tried setting FontAntialiasing=off?

**Comment by pas-de-2** [comment]
That fixes it! Awesome, thanks again.
