### ISSUE TITLE
The Guild 1 Steamversion

### ISSUE THREAD

**Issue by LPDaVinci** [narzoul/DDrawCompat#33]
Hey narzoul 
i dont know if ure still active on Github but i want to say thanks for your work on this dll injection.

Could it be possible to add Support for the Steam Version from TheGuild 1  the Binary Files Name are:
Europa1400Gold.exe
Europa1400GoldTL.exe
The normal GOG Version with GildeGold.exe  works but the cutted edges issue are just fixed on the gog version not on the steam one.

thanks alot

**Comment by narzoul** [comment]
I don't have the Steam version to try, but the GOG version seems to have the same two executables here. Maybe you have an older version installed?

Anyway, the normal (non-T&L) executable seems to work fine with v0.2.1 (experimental version doesn't show videos), and based on the feedback on a similar [Steam discussion](https://steamcommunity.com/app/39520/discussions/0/1290691937718270447/) it should work with that version as well. What issues did you have with it?

The T&L version uses Direct3D 8, which isn't based on DirectDraw, so can't be fixed in the scope of this project. For some reason it still loads ddraw.dll as well, but it doesn't seem to use it at all, so it won't be any help. In fact, it's probably counter-productive to use DDrawCompat with that because the user-mode display driver hooks may interfere with the normal functioning of Direct3D 8 (it wasn't designed for that).

---

This project is not abandoned btw, I just have very limited time to work on it and I'm currently busy rewriting the GDI emulation code to better support windowed apps and multiple monitors, and to fix some long-standing issues with it along the way. It's expected to still take some weeks to be completed and I probably won't be able work on other issues until then.

**Comment by LPDaVinci** [comment]
GOG Version Works with GildeGold.exe
The STEAM Version works with: TL.exe. I guess steam was chaning the filenames on their server..
11692 23:22:05.604 Process path: C:\Program Files (x86)\Steam\steamapps\common\Europa 1400 The Guild - Gold Edition\Europa1400Gold_TL.exe
11692 23:22:05.604 Loading DDrawCompat from C:\Program Files (x86)\Steam\steamapps\common\Europa 1400 The Guild - Gold Edition\DDRAW.dll
11692 23:22:05.605 DDrawCompat loaded successfully
10520 23:22:06.690 Installing DirectDraw hooks
10520 23:22:06.817 Installing GDI hooks
10520 23:22:06.823 Installing registry hooks
10520 23:22:06.823 Finished installing hooks
11692 23:22:33.920 Detaching DDrawCompat
11692 23:22:33.931 DDrawCompat detached successfully

I need to change compatiblity on windows 10 to windows 8.
Ddraw 0.2.1

**Comment by narzoul** [comment]
Videos should work now also in the experimental release.

Alt-tabbing seems to be blocked by the game itself. There may be a way around it, but I'll probably only be able to fix it much later with some config option.
