### ISSUE TITLE
MSAA makes a border around the game

### ISSUE THREAD

**Issue by De-M-oN** [narzoul/DDrawCompat#344]
When using MSAA, there is a border around the game like seen here:
<img width="1920" alt="Breakneck Screenshot 2024 08 09 - 19 17 46 82" src="https://github.com/user-attachments/assets/c456433f-becf-4170-8104-592d46394656">

When using Alternate Pixel Center its at least gone from top and left side, but therefore at the bottom.
Can we fix it? This issue is not happening with dgvoodoo 2.

**Comment by narzoul** [comment]
Which game is it?

**Comment by De-M-oN** [comment]
NICE 2

**Comment by narzoul** [comment]
It seems to be only a problem when changing settings dynamically with the config overlay, no?

**Comment by De-M-oN** [comment]
I personally have it always. Just turning MSAA entirely off fixes it.

`# AlignSysMemSurfaces     = on
 AltTabFix               = keepvidmem(1)
AlternatePixelCenter    = on
Antialiasing            = msaa8x(7)
# BltFilter               = point
# ColorKeyMethod          = auto
# ConfigHotKey            = shift+f11
# ConfigRows              = allrw, allro
# ConfigTransparency      = alpha(90)
 CpuAffinity             = all
 CpuAffinityRotation     = off
# CrashDump               = off
# DepthFormat             = app
# DesktopColorDepth       = initial
# DesktopResolution       = desktop
DisplayAspectRatio      = display
DisplayFilter           = spline(3)
 DisplayRefreshRate      = desktop
# DisplayResolution       = desktop
# DpiAwareness            = permonitor
# FontAntialiasing        = app
# ForceD3D9On12           = off
 FpsLimiter              = flipend(120)
 FullscreenMode          = borderless
 LogLevel                = none
 PalettizedTextures      = on
# RemoveBorders           = off
# RenderColorDepth        = appd8
 ResolutionScale         = display(1)
# ResolutionScaleFilter   = point
# SoftwareDevice          = rgb
SpriteDetection         = zconst
# SpriteFilter            = app
SpriteTexCoord          = clamp
# StatsAggregateTime      = 3
# StatsColumns            = label, cur, avg, min, max
# StatsHotKey             = shift+f12
# StatsPosX               = right
# StatsPosY               = top
# StatsRows               = label, presentrate, fliprate, blitcount, lockcount, ddiusage
# StatsTransparency       = alpha(75)
# StatsUpdateRate         = 5
# SupportedDepthFormats   = all
# SupportedResolutions    = native, 640x480, 800x600, 1024x768
# SupportedTextureFormats = all
# TerminateHotKey         = ctrl+alt+end
TextureFilter           = af16x
# ThreadPriorityBoost     = on
 VSync                   = off
# VertexBufferMemoryType  = sysmem
# WinVersionLie           = off
`

This is the config I use. zconst and clamp fixes the black line under the tach which is cool.

**Comment by narzoul** [comment]
Ok, I understand the problem now. The game's internal software vertex processing engine generates vertex coordinates that only cover about 90% of the last pixel row/column. E.g. if the internal resolution is 640x480, then the rendering is constrained to (0, 0)-(639.9, 479.9) instead of (0, 0)-(640, 480). This may be made worse by resolution scaling, e.g. at your current settings I think the internal resolution is 1280x720 upscaled to 3840x2160, so that would give (1279.9, 719.9) -> (3839.7, 2159.7), so the covered area actually shrinks to just 70% at the bottom and right edges.

This is less of a problem without MSAA, because the pixel center is still covered, so the entire pixel gets a new color. But with MSAA, some subpixel samples may fall into the uncovered area, which will then retain the previous color and will be blended with the covered part's color for determining the final pixel color. This is what causes the discoloration of the bottom and right edges.

I'm fairly certain dgVoodoo should also be affected by this, but I didn't find any AlternatePixelCenter or similar setting in it to test it properly, so only the top and left edges are discolored. By default, this is hidden by its "Deframer size" setting of 1, which removes a 1 pixel border around the image.

There are multiple workarounds I can think of, but each would require some new setting:
- Add a "dreframer" like dgVoodoo to just hide the ugly edges, but I don't really like this solution.
- Scale the viewport slightly so that the edges are properly covered. This could be done practically for free when ResolutionScale is also used, because only the scale factor would have to be adjusted. It might cause further problems with sprite coordinates though. But if needed, sprites could be excluded from the extra scaling based on the SpriteDetection setting.
- Any vertices that fall close to the uncovered area of the last pixel row/column could be clamped to the bottom/right edge of the pixel, based on some configurable threshold. This avoids having to scale up everything (including sprites) but has some extra performance cost because it needs to be limited to vertices within the uncovered pixel areas. It can also slightly distort the image in an uneven way, though probably it wouldn't be noticeable.

I'll probably go with the scale option for now.

**Comment by narzoul** [comment]
Does this fix  the issue? [ddraw.zip](https://github.com/user-attachments/files/16697873/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/16697875/diff.txt) compared to v0.5.3)

For now it's hardcoded to do a 0.1 pixel adjustment, but it can easily be made configurable if it works. It seems to fix the issue on my end.

**Comment by De-M-oN** [comment]
Yes, fixes it when Alternate Pixel Center kept enabled.

**Comment by narzoul** [comment]
Fixed in v0.5.4. Use ViewportEdgeFix=scale(10).
