### ISSUE TITLE
COMPETITIONS AT ROSEMOND HILL colour issue

### ISSUE THREAD

**Issue by BEENNath58** [narzoul/DDrawCompat#354]
This game is a part of the "Let's Ride! The Rosemond Hill Collection".

The colours in the game render incorrectly, regardless of running it native or with DDrawCompat
![rosemondhill](https://github.com/user-attachments/assets/8df0bc4b-404e-48c6-8ed7-907ba9af2254)

Can you please look into the issue? Seems somewhat new to me

**Comment by narzoul** [comment]
Luckily, I have the same difference on my Intel and NVIDIA GPUs. A quick look at the used resource formats in DDrawCompat logs reveals some key differences.

These lines are missing on Intel:
Using resource format: D3DDDIFMT_X8L8V8U8, texture, managed
Using resource format: D3DDDIFMT_X8L8V8U8, mipmap texture, vidmem

These 2 lines on NVIDIA:
Using resource format: D3DDDIFMT_X8L8V8U8, mipmap texture, managed
Using resource format: D3DDDIFMT_X8L8V8U8, texture, vidmem
are replaced by these 2 lines on Intel:
Using resource format: D3DDDIFMT_X8R8G8B8, mipmap texture, managed
Using resource format: D3DDDIFMT_X8R8G8B8, mipmap texture, vidmem

The D3DDDIFMT_X8L8V8U8 format is not supported on Intel. As far as I know, this format would be used for bump mapping. But somehow I doubt the game wants to use it for that, especially if it uses X8R8G8B8 as a replacement, which makes no sense. Maybe it just tries to find any 24 bit format, it happens to find that bump map format first, but it doesn't check that it's not an RGB format, and uses it by mistake.

Anyway, removing bump map texture formats from enumeration fixes it. In DDrawCompat, you can use the SupportedTextureFormats=argb setting.

**Comment by narzoul** [comment]
I just remember another game, Roller Coaster Mania 1, has similar issues. It turns out the same solution works for that too. I guess they use the same engine.

**Comment by huh02** [comment]
There is more to add line 
VertexBufferMemoryType=vidmem
![Uploading rider-mess.jpg…]()
otherwise I get mess when selecting the rider.

**Comment by narzoul** [comment]
What GPU is that? I can't reproduce it with either Intel, AMD or NVIDIA. It looks as if your vertex buffer gets corrupted by some invalid write or buffer overflow elsewhere. If your GPU has dedicated memory, then likely this is why putting the vertex buffer in video memory protects it better. I can try to add some code to detect this case, for testing purposes.

**Comment by huh02** [comment]
GTX 950.

**Comment by BEENNath58** [comment]
> What GPU is that? I can't reproduce it with either Intel

I can reproduce it on Ivy Bridge Intel HD Graphics

**Comment by narzoul** [comment]
> I can reproduce it on Ivy Bridge Intel HD Graphics

And is it fixed by VertexBufferMemoryType=vidmem? I think for integrated GPUs it should make no difference, since both are ultimately in system memory. But this makes it even more likely that it's some kind of memory corruption then.

**Comment by BEENNath58** [comment]
> And is it fixed by VertexBufferMemoryType=vidmem

That's correct. Vidmem setting works on Intel iGPU, while Nvidia 1050Ti works with both vidmem and sysmem settings

**Comment by ghotik** [comment]
Hi, Narzoul, thanks so much for the precious help.
I am trying to replicate the fix in DxWnd and I think that the EnumTextureFormats method could be a good place.
I'd like to ask you if you made the patch also at the d3dumddi level. I tried to browse your code and found some link to the EnumTextureFormats method, but I couldn't track any d3dumddi callback able to do the same thing in a deeper and more generalized way. Can you suggest me if this is possible and, in the affirmative case, which callback should be hooked?

**Comment by narzoul** [comment]
For the UMD, that would be the [GetCaps](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dumddi/nc-d3dumddi-pfnd3dddi_getcaps) function from [D3DDDI_ADAPTERFUNCS](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dumddi/ns-d3dumddi-_d3dddi_adapterfuncs), with the pData->Type parameter set to either D3DDDICAPS_GETFORMATCOUNT or D3DDDICAPS_GETFORMATDATA. Both together describe the supported formats. Be aware that on some runtimes (e.g. DX9) and driver versions, the same format may be returned multiple times with different capabilities, so each instance would have to be filtered.

In DDrawCompat, I used EnumTextureFormats for the filtering, because doing it at the UMD level would also prevent me from creating helper surfaces with the excluded formats.

**Comment by narzoul** [comment]
@huh02 @BEENNath58 For the graphics corruption, please reproduce it with this version (without VertexBufferMemoryType=vidmem):
[ddraw.zip](https://github.com/user-attachments/files/16828407/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/16828408/diff.txt) compared to v0.5.4)

In my case, the game creates these 4 vertex buffers at this point:
```
11:43:44.472 VertexBuffer: &039B4200 Address: &0BDC0920 Size: 320000 AllocationBase: &0BD70000 BaseAddress: &0BDC0000 RegionSize: 3862528
11:43:45.722 VertexBuffer: &039B4460 Address: &0BE10E40 Size: 280000 AllocationBase: &0BD70000 BaseAddress: &0BE10000 RegionSize: 3534848
11:43:45.724 VertexBuffer: &039B3B80 Address: &1082A8A0 Size: 1224 AllocationBase: &10720000 BaseAddress: &1082A000 RegionSize: 1081344
11:43:45.724 VertexBuffer: &039B3020 Address: &1091AD40 Size: 42696 AllocationBase: &10720000 BaseAddress: &1091A000 RegionSize: 98304
```

The size=42696 one is the rider's model, which is a static model that is only locked/unlocked once. I added write-protection to most of its memory pages after the unlock. Hopefully, this will crash your games before the model gets corrupted. If this happens, please enable also the LogLevel=debug and CrashDump=full settings, and share both the log and dmp files. Though most likely the corruption comes from within Rosemond.exe and I won't have time to reverse engineer what causes it.

**Comment by huh02** [comment]
Game crashed.
Rename .zip to 7z.
[logCompetitions at Rosemond Hill.zip](https://github.com/user-attachments/files/16828598/logCompetitions.at.Rosemond.Hill.zip)

**Comment by narzoul** [comment]
Well, that didn't crash where I expected. Actually that crash is caused by a debug logging bug in DDrawCompat, since some struct fields are not present on Windows 7. I just removed the logging of those fields for now, until I figure out a better solution.
Please try again with this version:
[ddraw.zip](https://github.com/user-attachments/files/16828683/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/16828685/diff.txt) compared to v0.5.4)

**Comment by BEENNath58** [comment]
For me, if I have set the VertexBuffer as sysmem, it crashes in the rider screen. When set to vidmem, it renders correctly and runs.

With the previous build, the rendering would be corrupted but wouldn't crash with sysmem

**Comment by huh02** [comment]
New logs here. 
Rename 001.zip and 002.zip to 7z.001 and 7z.002.
[2Competitions at Rosemond Hill.001.zip](https://github.com/user-attachments/files/16829236/2Competitions.at.Rosemond.Hill.001.zip)
[2Competitions at Rosemond Hill.002.zip](https://github.com/user-attachments/files/16829243/2Competitions.at.Rosemond.Hill.002.zip)

**Comment by narzoul** [comment]
Thanks! It looks like it might not be heap corruption after all. The difference in your logs compared to mine is that in your case, the IDirect3DVertexBuffer7Vtbl::Optimize method actually does something. It destroys the original vertex buffer and creates a new one, presumably with the optimized vertex content. But either it does something incorrectly, or there is some other interworking I'm not aware of. For me, the method simply returns 0 without touching the original vertex buffer, unless using video memory, in which case it fails when trying to create the new buffer.

I tried to compare the Windows 7 and 11 implementations of d3dim700.dll in IDA, and it looks like the Optimize implementation may have been nuked in newer Windows versions. Probably not a big deal, because I doubt it had much (if any) effect on modern hardware.

Anyway, I opted to try to fix it by removing the Optimize step in your case too. See if this works:
[ddraw.zip](https://github.com/user-attachments/files/16829777/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/16829779/diff.txt) compared to v0.5.4)

**Comment by huh02** [comment]
Unfortunately, the game crashes again during Chose rider. Here are the logs.
Delete the .zip extension.
[3Competitions at Rosemond Hill.7z.001.zip](https://github.com/user-attachments/files/16829862/3Competitions.at.Rosemond.Hill.7z.001.zip)
[3Competitions at Rosemond Hill.7z.002.zip](https://github.com/user-attachments/files/16829870/3Competitions.at.Rosemond.Hill.7z.002.zip)

**Comment by narzoul** [comment]
Oh, sorry, I think I attached the previous version again by accident. I updated the download link in my previous post with the correct version, please download it again!

**Comment by huh02** [comment]
OK, this one works fine, no crashes, perfect.

**Comment by BEENNath58** [comment]
I tested it on my Intel HD Graphics on Win7 and it works fine with both vidmem and sysmem
