### ISSUE TITLE
Fullscreen in DDrawCompat

### ISSUE THREAD

**Issue by BEENNath58** [narzoul/DDrawCompat#361]
While running games without DDrawCompat, I often get into an issue that games running in exclusive fullscreen (or the quasi-windowed mode that Windows uses nowadays) causes it to crash or a black screen with the game running behind it.

The same phenomenon is seen in DxWnd when using it to not "Run in Window'.

However DDrawCompat successfully succeeds to run the games in exclusive or even bordered/windowless modes.

While analysing the issue in DxWnd/Windows native, I come across a section that says:
```
EmuBlt: Lock ERROR res=0x80070057(DDERR_INVALIDPARAMS) @3911
EmuBlt: lpDDSEmu_Back=0 swSize=108
sBlt ERROR: Color conversion failed res=0x80070057(DDERR_INVALIDPARAMS)
```

In my understanding, Windows isn't able to set the game colours to display.

Is DDrawCompat doing some kind of color conversion that, isn't allowed in the native Windows quasi-windowed or fullscreen modes? Or is it something different?

**Comment by narzoul** [comment]
Those logs seem very DxWnd-specific. I also never heard of this problem. Can you give an actual example game? Preferably a 2D one, because Direct3D cannot be traced by API Monitor.

**Comment by BEENNath58** [comment]
> Can you give an actual example game? Preferably a 2D one, because Direct3D 2-7 cannot be traced by API Monitor.

Sure, I was explicitly testing **Hoyle Casino Empire** by Sierra. There are many more games that DDrawCompat fixes in this fashion

**Comment by narzoul** [comment]
This game doesn't have a black screen issue for me. Well, it does on first start if you haven't kickstarted the DWM8And18BitMitigation shim yet, but at that point it just displays an error message and exits. After setting Reduced color mode to 16-bit in Compatibility, it launches with a typical discolored picture on the left hand half of the screen (the movies play fine).

It's an issue with the DWM8And18BitMitigation shim. The primary surface can only be 32-bit since Windows 8. DWM8And18BitMitigation pretends to the application that it has the same bit depth that it requested (16 in this case), but the actual video memory surface is still 32 bit. This mainly causes a problem with games that lock the surface for CPU access, since the CPU expects a 16-bit color buffer but gets a 32-bit color one. So for every pixel column, it pushes 2 bytes of data instead of 4 per row, which causes the bad colors and half filled screen.

I don't know why they still haven't bothered to fix this. It's one of the first things DDrawCompat fixes since the beginning (actually that's why I originally created it). When the application requests to create a primary surface, DDrawCompat creates both a real primary surface (32-bit), and another surface at the requested color depth. It gives only the second surface to the application, so CPU access will behave as expected. When the application modifies that surface, it marks it as dirty and periodically (once per VBI) copies it to the real primary surface, so that it's actually displayed to the user.

**Comment by BEENNath58** [comment]
Thank you, the explanation helped. Helps with the fact where I need to check the DWM8AND16BITMITIGATION shim in games and how it is expected.

I had yet another doubt:
1. I saw some games (like Turok 2 or Daytona USA or Messiah) have borders in the game. Somehow DDrawCompat manages to remove them, although not running in exclusive mode. What's the mechanism? I assume you didn't use ForceSimpleWindow?
2. DDrawCompat uses the old WinNT style window. How does it help? And how much when compared to using the Windows Vista basic style?

**Comment by narzoul** [comment]
> I saw some games (like Turok 2 or Daytona USA or Messiah) have borders in the game. Somehow DDrawCompat manages to remove them, although not running in exclusive mode. What's the mechanism? I assume you didn't use ForceSimpleWindow?

In borderless windowed mode, DDrawCompat creates its own topmost fullscreen window (without borders) and redirects presentation to that. The borders on the original fullscreen window are probably still there underneath.

> DDrawCompat uses the old WinNT style window. How does it help? And how much when compared to using the Windows Vista basic style?

It's not related. I disabled window themes because I wasn't able to hook the theme drawing APIs properly, so there were glitches and missing graphics when some of the themed GUI elements were supposed to be drawn on the DirectDraw primary surface. I also wouldn't know how to draw the modern DWM borders (on the DirectDraw primary) that are nowadays composited by DWM, and not painted by the application.

**Comment by BEENNath58** [comment]
alright then its not a big deal then, thank you
