### ISSUE TITLE
.ini file

### ISSUE THREAD

**Issue by AlfredoDore** [narzoul/DDrawCompat#365]
It's not a problem, but a question
I'm trying to make an .ini file for game configuration, but the game always returns to the regular configuration, I would like to know better how to do it, it always ends up making a log file, in which even if I change its statistics they are not applied
![image](https://github.com/user-attachments/assets/855fe436-3c75-497c-8634-d056777a7dac)

**Comment by BEENNath58** [comment]
You have to make  file named "DDrawCompat.ini". Make sure that the extension is visible, else you may end up with a .txt file.

Put the setting in the format, for example:
`AllignSysMemSurfaces = on`

**Comment by narzoul** [comment]
Well, as you can see the log file already shows you the exact paths and filenames from which configuration is read, and none of those files exist.

Most likely, you're naming the file incorrectly. If you're using the Windows built-in File Explorer, make sure that file extensions are not hidden, so that you can check the full file name.
For Windows 11, see instructions here:
https://www.elevenforum.com/t/show-or-hide-file-name-extensions-for-known-file-types-in-windows-11.898/#One
For older Windows versions, see here:
https://www.techadvisor.com/article/734213/how-to-show-or-hide-file-extensions-in-windows-10.html
