### ISSUE TITLE
Cursor resolution scaling

### ISSUE THREAD

**Issue by gelebflamefinger** [narzoul/DDrawCompat#374]
I was wondering whether it would be possible to have the mouse cursor operate off of your desktop resolution, rather than the game resolution. For example, playing Tiberian Sun on a monitor with a resolution of 2560x1440 and a game resolution of 1280x720, the game is scaled up perfectly by a factor of 2, but the mouse feels much faster than my desktop mouse. I'm not sure if this request makes sense, and if it does, if it's even possible.

**Comment by narzoul** [comment]
I added an experimental MouseSensitivity setting in this patch:
[ddraw.zip](https://github.com/user-attachments/files/17607785/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/17607786/diff.txt) compared to v0.5.4)

It can be adjusted also through the config overlay, though note that it doesn't affect the overlay's cursor itself.
By default, it attempts to match the desktop sensitivity, but it can be made faster or slower with the Scale parameter.

**Comment by gelebflamefinger** [comment]
Thank you for taking a look at this!

It seems, with MouseSensitivity set to desktop(100), I lose the ability to move my cursor diagonally -- it's locked into moving straight up and down or straight left and right.

**Comment by narzoul** [comment]
That's bizarre. So what happens when you move the mouse diagonally? Does it move either horizontally or vertically at all? Does it alternate between the two? Does the movement at least seem proportional to the amount of movement in that direction?

Do you have some other software installed that could be interfering with the mouse? Did you tinker with mouse speed/acceleration settings in Windows, in the registry or any other way?

Which game are you testing? Are you using a DirectInput wrapper or any other hooks with it?

**Comment by narzoul** [comment]
I managed to reproduce by a combination of the following settings:
- Disable "Enhance pointer precision" in the Windows mouse settings
- Set the mouse pointer speed to less than 10 in the Windows mouse settings
- Set a high mouse polling rate (1000 Hz)

I understand the problem now. When "Enhance pointer precision" is off, a different algorithm will be needed. I'll add a new patch when I have some time to fix this.

**Comment by narzoul** [comment]
Here's the second attempt: [ddraw.zip](https://github.com/user-attachments/files/18223359/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/18223361/diff.txt) compared to v0.5.4)

Now it should work with enhanced pointer precision turned off too. I also added a "noaccel" option in case someone wants to have acceleration off in the game, but still on in Windows.

**Comment by gelebflamefinger** [comment]
Works flawlessly. Thank you for implementing this!

**Comment by automatedbugreportingfacility** [comment]
@narzoul: It looks like Wild Wild West: The Steel Assassin regressed with the new default value of this setting (`desktop(100)`) -- there are problems with upper-left diagonal mouse movements with DPI scaling == 150%. Much more pronounced with "No Page Flipping", a lot less with "Double buffer", but also present. Is that something you'd consider looking into, or should I just revert to the `native` setting?

**Comment by narzoul** [comment]
Is that with DpiAwareness set to unaware? With what version of Windows?

**Comment by automatedbugreportingfacility** [comment]
Yup, only `DpiAwareness = unaware` doesn't corrupt the cursor with DPI scaling > 100% (#319); Windows 10 22H2.

**Comment by narzoul** [comment]
Ah, I remember now. This is the game that constantly calls SetCursorPos for no reason. From a quick check, removing those calls does fix the problem. But I'll check later if it's possible to make it coexist with the MouseSensitivity setting somehow.

**Comment by narzoul** [comment]
Actually it doesn't seem to be an issue with MouseSensitivity specifically. It happens with the native setting too, if you have low enough native sensitivity (e.g. in Windows mouse settings) and try small mouse movements. It's just not as biased in any particular direction, but it's still very janky as the cursor is constantly pulled back towards the original position for small movements. You can't make the mouse move at an even pace.

I think the problem is that in DPI unaware mode, there is a separate low resolution, DPI unaware cursor coordinate (that the game sees), and a native high resolution, DPI aware coordinate that Windows stores. When you make a small movement, it might not change the low resolution coordinates at all, while still slightly changing the high resolution one. Then the game does something like GetCursorPos+SetCursorPos with the low resolution coordinates, which also resets the high resolution coordinates to whatever the low resolution one maps to, bringing the cursor back to where it was in both coordinate spaces and effectively reverting the movement.

I don't see a simple workaround for it. It should probably be patched out of the game, but I'm not sure where, there are a lot of DLLs and the stack trace doesn't show exactly which ones these calls are coming from.

**Comment by automatedbugreportingfacility** [comment]
> Then the game does something like GetCursorPos+SetCursorPos with the low resolution coordinates, which also resets the high resolution coordinates to whatever the low resolution one maps to, bringing the cursor back to where it was in both coordinate spaces and effectively reverting the movement.

Is that something that could potentially be improved with a custom implementation of Get/SetCursorPos() in the wrapper? For example, would it be possible to discard `SetCursorPos()` calls that wouldn't result in any changes to the low resolution coordinates but would affect their high resolution counterpart? Could be a no-op if DPI scaling == 100%. Other games using those functions (in a less pathological way) might also benefit.
