### ISSUE TITLE
Starsiege Blackscreen When Switching to OpenGL

### ISSUE THREAD

**Issue by PlagueDog** [narzoul/DDrawCompat#376]
DDrawCompat is presenting a black screen when Starsiege is set to use OpenGL. DDrawCompat v0.2.1 doesn't have this issue. It the blackscreen starts in v0.3.0 and up.
[DDrawCompat-v0.2.1-Starsiege_4.log](https://github.com/user-attachments/files/17427206/DDrawCompat-v0.2.1-Starsiege_4.log)
[DDrawCompat-v0.3.0-Starsiege_4.log](https://github.com/user-attachments/files/17427207/DDrawCompat-v0.3.0-Starsiege_4.log)

**Comment by narzoul** [comment]
OpenGL is not supported. If you want to use OpenGL, don't use DDrawCompat.

**Comment by Jenetrix** [comment]
Starsiege (As well as Starsiege:Tribes) use DDraw calls even when in Glide and OpenGL Remdering modes. 

Older versions of DDrawCompat work but support was regressed.

Please re-open.

**Comment by narzoul** [comment]
I do not intend to fix this because it's likely a considerable effort with minimal overall benefit. Very few games use multiple APIs simultaneously like this, and I have no idea how these APIs can interwork, nor do I have the time or interest in researching it. I thought I already added a note about this in the Readme, but if not I will fix that.

> Older versions of DDrawCompat work but support was regressed.

It was never intended to be supported. It may have worked in very old versions by coincidence, but those versions were also considerably simpler.
Only DirectX 1-7 and (partially) GDI are supported. This is very unlikely to change in the near future (read: next couple of years).
