### ISSUE TITLE
Jazz Jack Rabbit 2: The Secret Files

### ISSUE THREAD

**Issue by Hexaae** [narzoul/DDrawCompat#377]
Menu, in-game, etc. run fine. Quit screen after you Exit the game (there's a bye bye screen with some info) has issues: slow, black-screen for 3 secs, not working as expected. Won't happen if you don't use ddraw.dll wrappers.

![Jazz Jackrabbit 2 21_10_2024 02_08_19](https://github.com/user-attachments/assets/6f12c269-2eb8-467b-a50d-61964cebfd91)

Windows 11 23H2 (22631.4317), 4090 laptop with drivers 551.86, 2560x1600 16:10 screen 125% DPI.
Game Video options: 640x480x16 fullscreen.

[DDrawCompat-Jazz2.log](https://github.com/user-attachments/files/17460704/DDrawCompat-Jazz2.log)

**Comment by narzoul** [comment]
I don't know. On the GOG version, I have the opposite behavior: there is a slow, 3 second display mode switch with black screen before the credits show up, but with DDrawCompat it switches much faster, and it briefly shows the desktop (with a small black rectangle in the top left corner of it) instead of a full black screen.

Please set your LogLevel to debug and attach the debug logs.

> not working as expected

What else is not working as expected?

**Comment by Hexaae** [comment]
Logfile: 
[DDrawCompat-Jazz2.zip](https://github.com/user-attachments/files/17467590/DDrawCompat-Jazz2.zip)

Yes, it randomly shows a static credits screen, or black screen with music only until I press ESC again...

**Comment by narzoul** [comment]
I don't see anything suspicious in your logs. There is a brief ~0.3 sec break after pressing Enter on Quit, but that sounds normal to me. Presentation seems continuous afterwards, approximately every ~4 ms, with no errors. What did you see exactly until you pressed Escape later?

If you try to enable the stats or config overlays (shift+f11/f12) during the freeze, does it open and redraw continuously? Or does that not get displayed either?

**Comment by Hexaae** [comment]
Is there a way to force dGPU with DDrawCompat? I use an Advanced Optimus laptop with iGPU + auto-switch to dGPU and with DDrawCompat it seems to use iGPU even though I forced Windows 11's Graphics = force dGPU for Jazz2.exe...

shift+11 opens the DDrawCompat overlay (handy feature!) on a sluggish/flickering Credits screen!

**Comment by narzoul** [comment]
There is no way to do that with DDrawCompat. The older Optimus technology was explicitly restricted to using Intel for DX8 and older DX versions: https://nvidia.custhelp.com/app/answers/detail/a_id/3733/~/games-based-on-directx-8-and-older-versions-of-directx-will-only-run-on

I don't know if that also applies to Advanced Optimus. Never had an Optimus laptop myself.

In the logs you can check which driver is loaded from this line:
Hooking user mode display driver: C:\Windows\SYSTEM32\D3D9on12.dll+0xdee0

Since you haven't explicitly used the ForceD3D9On12=on setting, this would mean you're using an older version of the Intel GPU drivers, which defaults to D3D9On12 instead of a native DX9 driver. You could try updating your Intel drivers, since newer drivers (from the past several months) should automatically use the native driver. If that's not possible, you can try forcing the native driver anyway with ForceD3D9On12=forceoff. It may or may not run better. However, there are known issues with old versions of the native driver as well.

**Comment by Hexaae** [comment]
> If that's not possible, you can try forcing the native driver anyway with ForceD3D9On12=forceoff. It may or may not run better. However, there are known issues with old versions of the native driver as well.

This worked like a charm! Game runs better and Credits quit screen is now ok!

P.S.
In the meanwhile I tried also dgVoodoo and it fixed Credits screen, BUT I have to force dGPU in Win11 Graphics options, or will have issues with badly proportioned/out of screen display (only on the Credits screen).
