### ISSUE TITLE
Star Wars Rebellion

### ISSUE THREAD

**Issue by IllustriousProsperus** [narzoul/DDrawCompat#379]
The game itself works without problems (even the space battles!) but the colors are totally wrong
Wrong colors
![Wrong1](https://github.com/user-attachments/assets/178f1107-65fc-470e-8017-4c5e956abc71)
![Wrong2](https://github.com/user-attachments/assets/ff5adf54-cf4d-4203-a171-44903edaa881)

the game via 86box
![OK1](https://github.com/user-attachments/assets/e05c4d65-5e1e-426b-bd22-63eda509ea19)
![OK2](https://github.com/user-attachments/assets/cee2edb2-c99c-49de-a711-ecbe9247db0f)

Windows 11 x64 Radeon 6600xt 24.10.1

**Comment by narzoul** [comment]
It seems that I accidentally broke it with this commit: 483bf5f6dd51fcdef21a00da3ee7eab4477d7682
I can't understand why I changed useDefaultPalette to true instead of false, since it doesn't do anything for Carmen Sandiego, for which I originally made that patch. Hopefully it was just a mistake.

Anyway, we'll see with further testing if it breaks something else. For now I fixed it here:
[ddraw.zip](https://github.com/user-attachments/files/17517706/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/17517707/diff.txt) compared to v0.5.4)

**Comment by IllustriousProsperus** [comment]
Thanks, now the colors of the game are correct, BUT the initial cutscenes start with the colors are wrong, there is a sort of FLASH and then the colors adjust themselves (?). As you can see, here are the two screenshots in quick succession. I think there is something related to the depth of colors... of all the games tested so far it's the only one with this problem.
the beginning of the video
![Screenshot (57)](https://github.com/user-attachments/assets/82f1520c-45ec-4ecd-abfe-d2c35a8153ac)
after a "flash"
![Screenshot (58)](https://github.com/user-attachments/assets/ae3cd133-ed1d-4b8a-a368-ae44c3e95ea2)

**Comment by narzoul** [comment]
It's a thread scheduling issue. CpuAffinity=all should fix it.

**Comment by IllustriousProsperus** [comment]
Thanks, I confirm that the problem has been solved, I will now test other games.

**Comment by IllustriousProsperus** [comment]
Thanks, I confirm that the problem has been solved, I will now test other games.
