### ISSUE TITLE
Microsoft International Football 2000

### ISSUE THREAD

**Issue by IllustriousProsperus** [narzoul/DDrawCompat#393]
It just crashes

Crash dump
https://mega.nz/file/HJtwwJII#-xfXBJJXiLVzAPJSBnOcIjIkg7W3kP5Dd8uTA2bOF7o

Log
[DDrawCompat-MSIF2000.log](https://github.com/user-attachments/files/17604710/DDrawCompat-MSIF2000.log)

**Comment by narzoul** [comment]
The crash is caused by a bug in the game. It creates two Direct3D devices, but it still tries to use the first one after it was freed, even though it should be using the second one. It works correctly only once in a blue moon by coincidence, if the two interface pointers happen to fall on the same memory address.

Luckily, the FaultTolerantHeap shim of the Microsoft Compatibility Administrator can help avoid the crash. If you don't know how to use that, then just set the executable to Windows 8 compatibility mode, that should enable it automatically (along with other, probably unnecessary shims).

If there are still issues afterwards, then you might have a broken install as well. The game doesn't install for me on Windows 11. I had to do a full install on a Windows XP 32-bit VM and copy the files over. Afterwards, you should also copy the registry entries from `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft Games\International Football 2000\1.0` to `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft Games\International Football 2000\1.0` (or to the same path as on XP if you still use a 32-bit OS for some reason). Edit the paths in the copied registry keys as needed.

**Comment by IllustriousProsperus** [comment]
> The crash is caused by a bug in the game. It creates two Direct3D devices, but it still tries to use the first one after it was freed, even though it should be using the second one. It works correctly only once in a blue moon by coincidence, if the two interface pointers happen to fall on the same memory address.
> 
> Luckily, the FaultTolerantHeap shim of the Microsoft Compatibility Administrator can help avoid the crash. If you don't know how to use that, then just set the executable to Windows 8 compatibility mode, that should enable it automatically (along with other, probably unnecessary shims).
> 
> If there are still issues afterwards, then you might have a broken install as well. The game doesn't install for me on Windows 11. I had to do a full install on a Windows XP 32-bit VM and copy the files over. Afterwards, you should also copy the registry entries from `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft Games\International Football 2000\1.0` to `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft Games\International Football 2000\1.0` (or to the same path as on XP if you still use a 32-bit OS for some reason). Edit the paths in the copied registry keys as needed.

I confirm that compatibility with "Windows 8" is NECESSARY and the "WOW6432Node" string was missing.
Now everything works perfectly!

I tried to modify the exe by changing the "ddraw.dll" call to something else, it had no effect. With the hex editor it brings me to two strings with ddraw.dll maybe that's the main problem?

![International Football 2000](https://github.com/user-attachments/assets/608c4af1-2c37-4aaa-b06d-86acb6671e6c)

Changing the string to "ddraw.dll" to "fdraw.dll" causes a crash, "impossible to initialize direct 3d"

![iamerror](https://github.com/user-attachments/assets/09be951e-83fd-4f3a-8cf9-d09882f1bd86)

**Comment by BEENNath58** [comment]
> Changing the string to "ddraw.dll" to "fdraw.dll" causes a crash, "impossible to initialize direct 3d"

Why would you make the game not find DirectDraw? Obviously it will crash

**Comment by IllustriousProsperus** [comment]
> > Changing the string to "ddraw.dll" to "fdraw.dll" causes a crash, "impossible to initialize direct 3d"
> 
> Why would you make the game not find DirectDraw? Obviously it will crash

No not at all, sometimes games don't recognize when **_"ddraw.dll" is "external"_**. Sometimes it causes incompatibilities with some games. It happened to me with several games, for example Force 21, Dominant Species, Hype, Gangsters... A similar thing happens when some games have audio tracks (redbook data) Sometimes a generic **_"winmm.dll"_** wrapper is not enough. If the exe is not renamed the music will not work...

**Comment by BEENNath58** [comment]
> No not at all, sometimes games don't recognize when **_"ddraw.dll" is "external"_**. 

You will have to substitute the renamed hex with the renamed file. The game will search for whatever you put in the executable.

>  If the exe is not renamed the music will not work...

If you are testing this Redbook feature on Windows 11 then it's a completely different thing different from your current DirectDraw init issue

**Comment by IllustriousProsperus** [comment]
> You will have to substitute the renamed hex with the renamed file. The game will search for whatever you put in the executable.

that's what I wrote,

**_game.exe > ddraw.dll inside the game folder (narzoul/dgvoodo2/cnc) dosen't work
game.exe (changed the .exe via hex editor the string _ddraw.dll_ to _fdraw.dll_) > fdraw.dll inside the game folder (narzoul/dgvoodo2/cnc) works_**

> If you are testing this Redbook feature on Windows 11 then it's a completely different thing different from your current DirectDraw init issue

I just wrote this to say they have a similar problem... anyway the game works, now I'm testing other games.
