### ISSUE TITLE
DDrawCompat-thandor.log]

### ISSUE THREAD

**Issue by Alexhob123** [narzoul/DDrawCompat#397]
if i change displayaspectratio=display setting then save and open the game it still stays with the black border but if i close the game then open the file it changes back to app why does this happen am i doing it correctly here is my log if you want to chek it correctly and change it
[DDrawCompat-thandor.log](https://github.com/user-attachments/files/17689614/DDrawCompat-thandor.log)

**Comment by narzoul** [comment]
Are you editing the DDrawCompat-thandor.log file instead of DDrawCompat.ini? Otherwise it shouldn't automatically change back.

The log file clearly says that none of the potential configuration files exist:
```
22:56:37.094 Loading global config file: C:\ProgramData\DDrawCompat\DDrawCompat.ini
22:56:37.094   File not found, skipping
22:56:37.094 Loading user config file: C:\Users\Alex\AppData\Local\DDrawCompat\DDrawCompat.ini
22:56:37.094   File not found, skipping
22:56:37.094 Loading directory config file: E:\Alex Old\Desktop\ThandorXP\DDrawCompat.ini
22:56:37.094   File not found, skipping
22:56:37.094 Loading process config file: E:\Alex Old\Desktop\ThandorXP\DDrawCompat-thandor.ini
22:56:37.094   File not found, skipping
22:56:37.094 Loading overlay config file: E:\Alex Old\Desktop\ThandorXP\DDrawCompatOverlay-thandor.ini
22:56:37.094   File not found, skipping
```

The simplest file to use would be the directory config file:
E:\Alex Old\Desktop\ThandorXP\DDrawCompat.ini

Also, make sure that file extensions are visible in File Explorer:
https://www.howtogeek.com/205086/beginner-how-to-make-windows-show-file-extensions/
Otherwise, if you simply create a new text file, it will have a hidden .txt extension. So even if you see "DDrawCompat.ini" in File Explorer, the full file name might actually be "DDrawCompat.ini.txt", which is wrong.

Here is the config file you need, just unzip this in your game directory:
[DDrawCompat.zip](https://github.com/user-attachments/files/17690804/DDrawCompat.zip)
It already has the correct name and extension.

**Comment by Alexhob123** [comment]
i am editing the DDrawCompat-thandor.log I don't even have a DDrawCompat.ini file

**Comment by narzoul** [comment]
I already spoon fed the solution to you in my previous comment, which you didn't seem to have read. Nor did you read the wiki as I told you in your previous issue thread.

Here is the solution for you one last time:
> Here is the config file you need, just unzip this in your game directory:
[DDrawCompat.zip](https://github.com/user-attachments/files/17690804/DDrawCompat.zip)
It already has the correct name and extension.

If you still can't get it to work, then I don't know how to help you.
