### ISSUE TITLE
Black Dahlia

### ISSUE THREAD

**Issue by callomello** [narzoul/DDrawCompat#403]
Hi there!

I'm a huge fan of this as it's helped me play some childhood games with little to no issue. I'm currently testing out Black Dahlia (it's the second game by the folks who made Ripper) and while it opens and works no issue it looks like the game runs too fast. Specifically when you rotate the screen in gameplay. I played around with all of the FPS limiter options but it didn't seem to do anything. I don't suppose anyone would be able to help?

Kind regards,
Katie

**Comment by callomello** [comment]
Hmm, okay, funny update. I just downloaded the debug build so I could attach the log but this version of the .dll is running the game properly. No idea why that's the case but apparently I solved my own issue, haha. Sorry for all this!

**Comment by narzoul** [comment]
> Edit: It's mainly the fact that the debug log is slowing down the game so not perfect but a start.

Yeah, that's probably it, although the debug build should be slower even without logging. You can try to disable or reduce the logs to normal levels with the "LogLevel=info" or "LogLevel=none" settings, and see if it still runs slowly enough.

I'll check if it can be fixed properly later.

**Comment by callomello** [comment]
I did a quick check with the other log settings and it goes back to being too fast (a little slower than the regular build but not ideal).
Thanks for taking a look!

**Comment by IllustriousProsperus** [comment]
With the normal/debug version the screen rotation goes at the speed of light, the "fpslimiter" is ignored, with dgv2 the fps limiter activated crashes the game.

https://github.com/user-attachments/assets/336f73b6-af46-428e-b5cb-467be4915809

**Comment by narzoul** [comment]
It can't be fixed with generic frame limiters. The game uses the Lock/Unlock DirectDraw APIs for drawing everything. Limiting it globally causes other problems, like uneven frame limiting, flickering cursor, or mouse clicks not registering most of the time. It needs to be patched in the game itself.

I think I found the relevant function to patch in bd_win.exe, and some delay is easy enough to add into it.

In the Brazilian Portuguese, French, Italian, and the v1.10 patched English version, the function's hex dump looks like this:
```
56 57 6A 00 8B 73 04 56 8B 3B 57 6A 00 6A 00 52
51 50 53 31 DB E8 86 42 01 00 89 D8 E8 3F 43 01
00 5F 5E C3 00 00 00 00 00 00 00 00 00 00 00 00
```

In the unpatched English versions, only 2 bytes are different:
```
56 57 6A 00 8B 73 04 56 8B 3B 57 6A 00 6A 00 52
51 50 53 31 DB E8 A6 42 01 00 89 D8 E8 5F 43 01
00 5F 5E C3 00 00 00 00 00 00 00 00 00 00 00 00
```

In the French version, the last line should be replaced with this:
`00 5F 5E 6A 0A 2E FF 15 94 A2 4B 00 C3 00 00 00`
In all other versions, it should be replaced with this:
`00 5F 5E 6A 0A 2E FF 15 94 82 4B 00 C3 00 00 00`

The `0A` byte in the replacement is the number of milliseconds to delay, so you can tweak it slightly if you want.

There are other problems with the game, like the cursor trails, but I don't have time to patch all of them.
None of those have anything to do with DDrawCompat, so I'm closing this issue.
