### ISSUE TITLE
Final release? -Question

### ISSUE THREAD

**Issue by WrathX** [narzoul/DDrawCompat#41]
Hi, just wondering if the release from Dec 2016 is going to be considered the final release or are you planning more in the future?

**Comment by narzoul** [comment]
If you're referring to the experimental release, it was actually last updated at the beginning of this year. It just shows 2016 because that's when the release was originally created and I only replace the tag (the linked commit ID) and the attachments from time to time. I guess the date is not updated unless the release is removed completely and then recreated.

So yeah, I'm planning more releases, but the next non-experimental version still seems at least a few months away at the current rate of progress.

**Comment by WrathX** [comment]
Ah ok I see what you mean. I appreciate the response. Thank you for the work you've put into this. It helped save an old mmo game. :)

**Comment by WrathX** [comment]
Actually just tried the latest version from January and it made the game I'm playing run a lot choppier, I'll stick with the older release :)

**Comment by WrathX** [comment]
Just wanted to post that the latest file from June 7th seems to help on a system to system basis for the game that I use it for (Project Visitor). It seems to work great with newer Nvidia cards like RTX series and GTX 1660ti for example but works worse with other cards like GTX 1060,1070, etc. Older version of the ddraw file works better with those cards. Again great work on this, thank you for what you have done.

**Comment by WrathX** [comment]
Just wanted to say that the latest couple or so experimental builds have been awesome! They have greatly improved frame rates and stability of the frame rates. Seems to work with most systems now as well that play the game. Amazing work you have done! Thank you!

**Comment by narzoul** [comment]
Thanks for the feedback! I'm glad things are going in the right direction. I wanted to check out this game, but I noticed it's subscription-only and doesn't have a trial period either, so I passed.

If you have time and willingness, I'd appreciate it if you could continue checking out future releases as well, and let me know if things turn for the worse, since I can't test either this game or NVIDIA cards currently. You should probably keep a backup of the current experimental release, just in case... :)

**Comment by WrathX** [comment]
Yes for sure, I have been trying every experimental release for the past few months now. I get emailed now when you update it so that is handy. Yep I always keep a copy of the old one handy. I'll keep checking out every update and let you know how things go. Plus we have a few players that are willing to try it out as well which helps check out different systems. Thanks again

**Comment by WrathX** [comment]
I noticed that you had 2 releases on Aug 11. I'm not sure what you changed but I noticed with the second you posted later in the day the frame rates fluctuate more, going down a bit now. The release earlier in the day and the couple before it show solid 60fps frame rates which I could not make drop below 60. The latest one has them fluctuate down to mid to low 50s. Not terrible but not as stable as the release before. 

Also just to note, I can't seem to get the frame rate to go above 60fps. Vsync is off everywhere (double checked). I usually run at 1920x1080 at 60fps but even if I go down to 1024x768 the frame rate will not go above 60. That is not a complaint just an observation (I am loving that I can run the game at 60fps lol).

**Comment by narzoul** [comment]
The performance drop could be similar to #47. I think it turned for the worse there with the same commit. On my system, the performance is actually better with the latest release than with the previous one, but that seems to be rather the exception than the rule at the moment.

As for the v-sync issue, from what I remember, the driver level v-sync control doesn't work with older APIs like DirectDraw on some drivers. Is there also an in-game v-sync option? If you can upload the debug logs with the ReleaseWithDebugLogs build (in ddraw-debug.zip), I could check if v-sync is really on or off in the related function calls at least.

**Comment by narzoul** [comment]
I've updated the experimental release with some performance related fixes. Please check if it's back to solid 60 fps again.

**Comment by WrathX** [comment]
Still fluctuating like it was. Also noticing some really really weird texturing issues with this one. From a distance, models in game have messed up textures. Only if you are really close to something does the texture look correct. I'll try to attach some pictures a bit later to explain.

**Comment by WrathX** [comment]
First of all when I say fluctuating, it will stick around 60 but sometimes just randomly go down to low 50s for a few seconds then goes back up. 
Look at the circles weapons, it's like the UV mapping gets all wonky at a distance. It happens on every single model in game.
![Project Visitor Screenshot 2019 08 19 - 19 58 09 67_LI](https://user-images.githubusercontent.com/40301929/63309426-683d5180-c2bc-11e9-9f40-8a5c0ac91c24.jpg)
This is how the weapon is supposed to look but only if I'm very close to it.
![Project Visitor Screenshot 2019 08 19 - 19 58 32 86](https://user-images.githubusercontent.com/40301929/63309446-7be8b800-c2bc-11e9-99e9-480d9b2f09de.png)

In this picture you can see part of a red logo on a flag, it's supposed to be centered. Actually every thing you see in this picture has messed up textures.
![Project Visitor Screenshot 2019 08 19 - 19 59 23 38_LI](https://user-images.githubusercontent.com/40301929/63309504-ad618380-c2bc-11e9-98fa-a1a9c57735ef.jpg)

This one I circled the transition where it starts to go wonky. As you move closer the texture fades in to how it's supposed to look. Very strange.
![Project Visitor Screenshot 2019 08 19 - 19 59 39 64_LI](https://user-images.githubusercontent.com/40301929/63309509-b05c7400-c2bc-11e9-9fc1-69edc4575324.jpg)

**Comment by narzoul** [comment]
Does the latest experimental release fix any of these issues?

**Comment by WrathX** [comment]
Yes the latest one did  fix the issue with the UV mapping on the textures not showing up properly.

**Comment by narzoul** [comment]
So the performance drop still remains?

**Comment by WrathX** [comment]
The frame rate does still drop a bit. I mean it doesn't go down below 50fps so the game still runs good, it's just not a solid 60fps like before.

**Comment by WrathX** [comment]
Today's seems to be holding pretty solid at 60fps, barely even dipping down to 59.

A note about the Aug 27th release, another person in the same game as me tested it and when he went in game, for some reason it made him spin around in circles really fast without being able to stop. He put the older ddraw.dll file back in from the beginning of Aug and it was fine. He hasn't tried today's release yet.

**Comment by WrathX** [comment]
The release from yesterday is running pretty stable for myself maybe dropping a frame here and there but no other noticeable issues. Another guy testing it though says that his frame rate went down and for some reason still makes his character spin around in circles staring at the sky. If he goes back to the old ddraw file it works fine. His system has a GTX1070 with an i7 (3.4ghz) wtih 32gigs of ram running Win 10. My system that it runs fine on has a GTX1060(3gb) Ryzen R5 2600 with 16gigs of ram running Win 10.

**Comment by narzoul** [comment]
The spinning issue sounds more like a problem with input handling than DirectDraw/Direct3D, and I don't remember touching anything related lately, at least directly. Your systems are pretty similar too (CPU shouldn't matter), so I think it's rather some driver/game config difference or interference from another software or compatibility setting.

Do you know which was the first release that introduced this exactly? Narrowing down the issue to a specific commit might give me some ideas.

Does the game have a windowed mode? Does the issue affect that too?

**Comment by WrathX** [comment]
The one that started doing this for him was the one released on Aug 28th. Nothing else had changed, no settings, no configs, nothing. He only replaced the ddraw.dll in the folder. It would do the spinning thing so he replaced it with an older one. The one he runs that works best for him is the Aug 11th one.

**Comment by narzoul** [comment]
I understand he didn't change any settings. I meant he might have some different settings from you since he has the problem but you don't. Could be related to multi-monitor setup or something like that too.

There were also releases on 19th and 22nd August, could he test those too to narrow it down further? I'll readd them here. Also there were 2 releases on 28th, I'll attach the first one of those too in case you were referring to the second.

Basically I'm interested in which was the last release that didn't have this issue and the first release that did. Afterwards, if there were multiple commits between those two releases, we might have to narrow it down further to a specific commit.

19th: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/3576531/ddraw.zip)
22nd: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/3576536/ddraw.zip)
28th: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/3576540/ddraw.zip)

**Comment by WrathX** [comment]
All of those have the same spinning issue for him. He runs 1680x1050 resolution. I tried that resolution and had no issues. We both run with single monitors.

**Comment by narzoul** [comment]
Of those commits, the DPI awareness related one is by far the most suspicious. Please have your friend test the game with DPI scaling set to 100% to see if it fixes the issue. To change it, right-click on the desktop, then choose "Display settings" from the menu, and change the value from the first drop-down list under "Scale and layout". Conversely, you could also test it yourself whether increasing the value from 100% can reproduce the issue.

If it turns out that DPI scaling is indeed the culprit, then please also check whether any of the DPI compatibility settings can be used to reproduce the problem with the older version from 11 Aug. These settings can be accessed by right-clicking on the executable, switching to the Compatibility tab and then clicking on the "Change high DPI settings" button. I think the one I tried to use from within DDrawCompat was the "Application" setting in the drop-down list at the bottom, but I'm not sure if that is exactly what I achieved.

**Comment by WrathX** [comment]
Ok I'll give those a shot. In all this there is one thing if forgot to mention that you may need to know. For most people the game needs to be run in Win7 compatibility mode in order for it to launch properly. I have noticed myself lately that I seem to be able to run the game without having to use Win7 mode. Right now I have the mode on. I'll try your above suggestions to test in the next day or so.

**Comment by WrathX** [comment]
I tried testing the above out myself and could not get it to replicate the problem

**Comment by narzoul** [comment]
Latest experimental release should fix the "spinning" issue. It should no longer be necessary to apply any DPI fixes to the executable file manually.

Let's track the other issues (if there are still any) in #62.

**Comment by patrikmore** [comment]
It's not an issue. Rather the opposite. Just I have to say that the new experimental release works better than dgvoodoo2, playing Flight Unlimited 3 game. As dgvoodoo2 no banding (smooth skies) but in addition game opens full screen all the time, more stable, no lags. Great at 1024x768. Just one little thing, I guess related with performance, but it happens with all the wrappers. Game is struggling to render video and the plane radio breaks sometimes (once an hour), just the sound channel for plane radio, with one bass pilot voice! I'm asking if there is a wrapper for dsound.dll or the sound output is already corrupt. That's why I thought it was related with performance. Anyway, it happens less than with dgvoodoo2.

**Comment by patrikmore** [comment]
I answer myself. I repared the voice sound problem of Flight Unlimited 3 with resviewer, cloning and renaming a similar pilot voice file.
But I insist, experimental last release of DDrawCompat works perfect with Flight Unlimited 3. Add it to the list. The previous stable version gives only sound (black screen).
