### ISSUE TITLE
DDrawCompat references in DxWnd

### ISSUE THREAD

**Issue by ghotik** [narzoul/DDrawCompat#414]
Hi.
I take advantage of this forum to post a non-technical issue.
Thanks to your support I was able to add some important features to DxWnd and it seemed to me fair to mention this in the DxWnd help pages. But before posting a new release I'd like you to acknowledge my preliminary draft that you can download here: https://sourceforge.net/p/dxwnd/discussion/general/thread/e12e00da4d/?page=2#15bc
The references are in the WDDM.html page, but you can unpack the hole archive in a temporary forder and get there through DxWnd.html to see how it would look integrated in the page frame.
Please, feel free to modify the WDDM.html content at your pleasure, or just say "ok".
p.s. I added also a nice "Space Bunnies Must Die" example thanks to the color key fix.

**Comment by narzoul** [comment]
Thanks, but whatever you put there is up to you and completely fine by me. I intentionally used the most permissive license I could, so that people could use DDrawCompat however they want, even without any separate permission, acknowledgement, credits, etc. You could copy the whole project into DxWnd without any mention of the source and it would still be fine by me!
