### ISSUE TITLE
hello narzou

### ISSUE THREAD

**Issue by 61960466** [narzoul/DDrawCompat#44]
Frist,thx your project,it great work,i uses new dll test several questions of feedback:
FPS is too high hope to limit 80-90，If fps to high ,play game is too leg,i use your dll play Diablo

**Comment by narzoul** [comment]
Diablo is limited to 20 fps by default (at least my version is). There is nothing special that needs to be done, it's how the game engine is built. What's your actual fps? Did you use some tool to measure it?
I'd recommend to check it with the tools available through your GPU control panel, because DDrawCompat isn't compatible with most 3rd party overlay/screen recorder tools at the moment.

Do you have some unofficial patches/mods installed? Are you using the recently released GOG version? (Unfortunately I don't have that, I have an old CD version).

**Comment by 61960466** [comment]
thx,i will down office Diablo client test it!:)
