### ISSUE TITLE
Hello, narzoul! The new version of the problem.

### ISSUE THREAD

**Issue by 61960466** [narzoul/DDrawCompat#45]
I Use new DDrawCompat's version tested different classic 2D old games with different hardware and found the following problems.
1, window mode switch full screen appears the program is not responding or black screen
2, some 2D games are developed with DDRAW, the material is BMP mixed dyeing, and some new graphics cards can't handle" D3DRENDERSTATE_COLORKEYENABLE". Can this be  solved?
Thanks again for letting us play the game of the year. :)

**Comment by narzoul** [comment]
Please give more details so I can easily reproduce the issues, otherwise the chances of a fix are next to 0.
Which games are affected by which issue exactly? On what OS version and what GPU? By "new DDrawCompat version" do you mean the experimental release?

Is the issue with Diablo fixed then? If yes, then please close it.
