### ISSUE TITLE
Jank issue with Desperados

### ISSUE THREAD

**Issue by mzso** [narzoul/DDrawCompat#5]
Hi narzoul!

Thanks for this! I found out about DDrawCompat only today, and I tested it with Desperados.

It was near flawless. There's only one issue. When I quicksave, there's around a 2 second hang. I think it's because some text is rendered at the bottom of the screen saying "game saved successfully".
I also get the hang when I press escape to pause the game, before the menu appears.

Here's a link to the demo if you want to test: https://archive.org/details/desperadosDemo

(I used the latest version: v0.2.1)

**Comment by mzso** [comment]
I noticed you made bunch of commits since v0.2.1. Maybe it's already fixed?
Do you plan to release release a new build?

**Comment by narzoul** [comment]
Well, the issue wasn't too difficult to track down. Fixing it, however, is another story.

The only problem seems to be that when e.g. the menu is opened, the game locks the back buffer and it takes a long time to update it. Probably it uses some access patterns that are simply inefficient on video memory. Although on my system it isn't as bad as you said and there is less than half a second delay between the lock/unlock.

To verify this theory, I forced all video memory surfaces to system memory with a quick hack, and that indeed got rid of the delay. The problem is that while this "solution" happens to work for Desperados, it could easily break other games. So that leaves us with these options overall:

1. Add a configuration option to enable this hack selectively, so it can be used with some games that can benefit from it without side effects.
2. Properly force all 2D operations into system memory for all games. I experimented with this earlier while trying to fix similar performance issues with Rogue Spear's menus, but there are some operations that unfortunately DirectDraw doesn't support in system memory, such as color conversions (whereas it is supported in video memory). So I'd have to find and implement workarounds for all the unsupported cases, which could be a lot of effort (especially to do it efficiently).
3. Ignore the problem as it isn't really serious in this case.

I don't like the 1st option at all, as it requires manual fiddling by the users for each game in order to find the right config, and that is something I've been very keen on avoiding so far, and I plan to keep it that way.

The 3rd option of course doesn't really benefit anyone, but at least it's very easy to do. :)
Unfortunately, even if we could agree that the problem isn't serious in this case, I have a feeling sooner or later someone will find a game where this could significantly cripple gameplay too, and it will no longer be possible to ignore it.

That leaves the 2nd option, which could take quite a while to implement and requires thorough testing. Still, I think this is the best option so I might give it another shot and see if I can get it into the next release.

As for the date of the new release: there are still several important issues that definitely need to be fixed first, and I might find additional ones once I start doing some heavier testing. It could take a few weeks to a few months. Hopefully I can finish it before the end of this year, but I can't promise anything.

In the meantime you could look into other projects like [DxWnd](https://sourceforge.net/projects/dxwnd/), which may already have options to force video memory surfaces into system memory. I already tried [Aqrit's ddwrapper](http://bitpatch.com/ddwrapper.html) but didn't have any luck with it (game either crashes on startup or has severe graphical issues making it unplayable).

Or if you can use an integrated video card, that could solve it as well since those usually don't have dedicated video memory, and use a reserved portion of system memory instead. I tested Intel HD 4600 and it can run the game smoothly, for example (with v0.2.1).

**Comment by mzso** [comment]
Thanks for looking into it.

> I don't like the 1st option at all, as it requires manual fiddling by the users for each game in order to find the right config, and that is something I've been very keen on avoiding so far, and I plan to keep it that way.

Well, it's a lot better than nothing. And it sounds like it doesn't take much to do. 

> Edit: dgVoodoo 2 can also run the game fine for me, without any quicksave/menu delays (tested with v2.53).

To me it just doesn't run at full speed with dgvoodoo, so the menu delay or lack of it is not really interesting. I'm not familiar with DXWnd, I'll have a look. I also tried wineD3D, which has a crashing bug (http://adolfintel.com/?p=wined3d/index.frag), when I move the mouse.

**Comment by mzso** [comment]
Hi!
Tried Desperados' sibling game: "Robin Hood: The Legend of Sherwood Demo" which was released one year later.
Curiously it runs way slower then full speed. But only the full game (GOG) is affected, the demo (web archive) still runs at full speed. It also shows the same hang when quicksaving.
The menu seems to run at full speed except when I hover over the the keyboard options, in which case it becomes extremely choppy. 
(I can't measure actual fps because msi afterburner causes these programs to fail.)

**Comment by narzoul** [comment]
I assume this has been fixed already. If it's not the case, please reopen it.
