### ISSUE TITLE
Laghaim Online crashes when switching tasks

### ISSUE THREAD

**Issue by marcelhxc1** [narzoul/DDrawCompat#51]
I cant use double window. Another problem is, if i use win10, and i go out of the game window, when i back it crash the app.

**Comment by narzoul** [comment]
1. What game are you talking about?
2. Which version of DDrawCompat did you use?
3. What do you mean by "double window"?
4. Do you mean you have tested other version of Windows and it doesn't crash there? Which versions?

Please choose a more descriptive title next time and add sufficient details to your problem reports so I can try to reproduce them, otherwise I can't do anything about them.

**Comment by marcelhxc1** [comment]
Hello

The game is Laghaim online ( is an old game mmorpg onlline ), double window
is open two windows to play with two different accounts.

The version of DdrawCompat is the latest on your releases.
I test only on win10 latest release ( this version if i use offboard
graphic cards like nvidia or radeon the fps decrease ).


Em sáb, 10 de ago de 2019 às 05:04, narzoul <notifications@github.com>
escreveu:

**Comment by marcelhxc1** [comment]
Olá,

Eu acabei de assinar o abaixo-assinado "Meu filho precisa de UTI móvel e 5
transplantes nos EUA. Acatem minha liminar JÁ!" e queria saber se você pode
ajudar assinando também.

A nossa meta é conseguir 150.000 assinaturas e precisamos de mais apoio.
Você pode ler mais sobre este assunto e assinar o abaixo-assinado aqui:

http://chng.it/XyXTxFxgQZ

Obrigado!
Marcel Bueno

**Comment by narzoul** [comment]
I can't reproduce either issues. Which version of the game do you use?
