### ISSUE TITLE
Dragging Window into second screen

### ISSUE THREAD

**Issue by die4teoffenbarung** [narzoul/DDrawCompat#54]
Hi again,
a friend has issues with [[www.d4o.info](https://www.d4o.info)] https://github.com/narzoul/DDrawCompat/commit/898c7e819c29a64face33f004f5e0cc8d400ba66 if he try to move the window to his 2nd screen, that's what he told me:
```
So at the 1st time the drag into another screen worked. 
The picture did not get stuck and reacted quite normally, "fullscreen"-window was not possible.
At the 2nd and 3rd times the client is already crashed when pulling over.
The desktop briefly overlaps the D4O Window on the desktop although you could click through it.
Was probably pure coincidence and luck working at the 1st time.
```

I attached all 3 Log-Files from him, first to third try. He is using Windows 10.
https://drive.google.com/file/d/10i_Asr05yJVorD4G33OchQ880e_vkeja/view?usp=sharing

Best regards!

**Comment by narzoul** [comment]
The freezing should be fixed in the latest experimental release.

As for stretching to full screen (or any stretching at all) on a secondary monitor, this is currently only supported when the desktop is set to 16-bit color mode. On Windows 8/10, the "Reduced color mode: 16-bit (65536 color)" compatibility setting can be used instead.

Also note that displaying a windowed app on a secondary monitor is currently not hardware accelerated, so it may be slightly slower than on the primary monitor. However, it should be more than fast enough for what this game needs (if it's anything like GoN and similarly capped at 32 fps).

**Comment by die4teoffenbarung** [comment]
Hi,
Works like a charme. Thanks a lot!

Best regards
