### ISSUE TITLE
Wipeout XL: almost perfect, it's just too fast

### ISSUE THREAD

**Issue by aybe** [narzoul/DDrawCompat#61]
(this is about the complete game, not the demo version)

File: Wipeout2.exe
SHA-1: ae06da74e2db32fd73a9d35da195e7c06cfca0f8

The game has no graphical glitches, everything looks perfect except for one thing: it's too fast.

Is there a way to slow things down in DDrawCompat like DxWnd can do ?

Thank you 🥇

**Comment by aybe** [comment]
Also, the debug version of DDrawCompat is slow enough to make it playable albeit it's a bit too slow then.

**Comment by narzoul** [comment]
There is no such feature currently. It could be added in a future version, but it would require config options, which is not something I've planned to add for the next major release. So it's quite a long way ahead (meaning possibly not even this year).

You could try using 3rd party frame limiters, or the one supported by your driver, though I didn't have any luck with AMD Chill on the demo version.
If you have an Nvidia GPU, you might be able to use Nvidia Profile Inspector to set v-sync to "1/2 Refresh Rate" which would give the expected 30 fps, assuming you have a 60 Hz display (and v-sync enabled).

I don't recommend using the debug build for this. It'll produce a very big log file unnecessarily.

I'm closing this because there is another open issue with the same request already: https://github.com/narzoul/DDrawCompat/issues/29

**Comment by aybe** [comment]
okay, thanks!
