### ISSUE TITLE
Pink artifacts on the game o2jam

### ISSUE THREAD

**Issue by jcgo16** [narzoul/DDrawCompat#79]
Hi its me again, i am testing the game called o2jam, and i use your experimental ddraw

i tried rx 580 and gtx 970 and it wont show any of the pink artifacts

![ScreenShot056](https://user-images.githubusercontent.com/24879672/102027143-1cd37000-3d57-11eb-864c-2c56ff530149.jpg)
![ScreenShot058](https://user-images.githubusercontent.com/24879672/102027146-1d6c0680-3d57-11eb-9945-4166bb1cfed9.jpg)

OS: Windows 10 Version 20H2 (OS Build 19042.685)
GPU: AMD RX 5700XT
Driver Version: Radeon Software Adrenalin 2020 Edition 20.11.3
CPU: Ryzen 9 3950X
RAM: 64GB

https://www.mediafire.com/file/w4hbmkf1bu57dau/O2Test.rar/file
that is the game, and this is the log file

https://www.mediafire.com/file/h9fsit54g7njqq4/DDrawCompat-Otwo.rar/file

some other users are experiencing the same thing. 
LOG FILE 2
https://1drv.ms/u/s!Ap1KPoeVglstwwV06rSEdu9s1ZVd?e=NIr7hX
LOG FILE 3
https://1drv.ms/u/s!AkT7DukTh_MjiK9qcEs0w6dKzm-Lgg?e=VAKcZo

this is the issue

**Comment by narzoul** [comment]
Well, it's obviously something wrong with the blits using source color key. I assume it's a driver issue because it only seems to affect the Radeon RX 5xxx series. I added a potential auto-detection of the problem for this case, and worked around it by emulating the broken feature in software if needed.

Please retest with the latest experimental release, since I don't have appropriate hardware to reproduce the issue.

**Comment by jcgo16** [comment]
Looks like it is working fine now. Thank you for the fix

**Comment by jcgo16** [comment]
Let me know if you need the new log file for the new fix

**Comment by narzoul** [comment]
No, if it works then it's fine. Thanks for the feedback!
